In [1]:
import pandas as pd
import numpy as np
import matplotlib
import readDataUtil
# from graph_tool.all import *

In [4]:
df_trajectories, df_travel_segment = readDataUtil.read_trajectory("../data/original_dataset/training/trajectories_table_5_training.csv")

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000

In [8]:
df_travel_segment

       link_id       starting_time  travel_time  day_of_week minute_block
0          105 2016-07-19 00:14:24         9.56            1         0000
1          100 2016-07-19 00:14:34         6.75            1         0000
2          111 2016-07-19 00:14:41        13.00            1         0000
3          103 2016-07-19 00:14:54         7.47            1         0000
4          122 2016-07-19 00:15:02        32.85            1         0000
5          105 2016-07-19 00:35:56        11.58            1         0020
6          100 2016-07-19 00:36:08         7.44            1         0020
7          111 2016-07-19 00:36:15        16.23            1         0020
8          103 2016-07-19 00:36:32         5.95            1         0020
9          122 2016-07-19 00:36:40       104.79            1         0020
10         105 2016-07-19 00:37:15         5.26            1         0020
11         100 2016-07-19 00:37:20         2.85            1         0020
12         111 2016-07-19 00:37:23         5.94            1         0020
13         103 2016-07-19 00:37:29         1.13            1         0020
14         116 2016-07-19 00:37:30        10.07            1         0020
15         101 2016-07-19 00:37:40         5.27            1         0020
16         121 2016-07-19 00:37:46        25.51            1         0020
17         106 2016-07-19 00:38:11         3.42            1         0020
18         113 2016-07-19 00:38:15        19.76            1         0020
19         110 2016-07-19 00:37:59        13.74            1         0020
20         123 2016-07-19 00:38:13         4.70            1         0020
21         107 2016-07-19 00:38:17         6.63            1         0020
22         108 2016-07-19 00:38:24         4.95            1         0020
23         120 2016-07-19 00:38:29         0.74            1         0020
24         117 2016-07-19 00:38:30        27.05            1         0020
25         105 2016-07-19 00:56:21        16.08            1         0040
26         100 2016-07-19 00:56:37        12.34            1         0040
27         111 2016-07-19 00:56:49        25.75            1         0040
28         103 2016-07-19 00:57:15         4.89            1         0040
29         116 2016-07-19 00:57:21        38.30            1         0040
...        ...                 ...          ...          ...          ...
763538     110 2016-10-17 23:40:19        11.87            0         2340
763539     123 2016-10-17 23:40:31         5.42            0         2340
763540     107 2016-10-17 23:40:37         3.92            0         2340
763541     108 2016-10-17 23:40:41         4.00            0         2340
763542     120 2016-10-17 23:40:45         0.60            0         2340
763543     117 2016-10-17 23:40:45        16.27            0         2340
763544     110 2016-10-17 23:52:18         7.59            0         2340
763545     123 2016-10-17 23:52:26         4.11            0         2340
763546     107 2016-10-17 23:52:30         2.37            0         2340
763547     108 2016-10-17 23:52:32         2.78            0         2340
763548     119 2016-10-17 23:52:35         0.63            0         2340
763549     114 2016-10-17 23:52:36        15.16            0         2340
763550     118 2016-10-17 23:52:51        18.23            0         2340
763551     122 2016-10-17 23:53:09        20.94            0         2340
763552     110 2016-10-17 23:53:57        10.56            0         2340
763553     123 2016-10-17 23:54:07         4.02            0         2340
763554     107 2016-10-17 23:54:11         2.28            0         2340
763555     108 2016-10-17 23:54:14         4.17            0         2340
763556     119 2016-10-17 23:54:18         1.44            0         2340
763557     114 2016-10-17 23:54:19        62.86            0         2340
763558     118 2016-10-17 23:55:22        22.62            0         2340
763559     122 2016-10-17 23:55:45        24.51            0         2340
763560     110 2016-10-17 23:54:35         9.10            0         2340
763561     123 2016-10-17 23:54:44         5.36            0         2340
763562     107 2016-10-17 23:54:50         3.09            0         2340
763563     108 2016-10-17 23:54:53         3.64            0         2340
763564     119 2016-10-17 23:54:56         0.82            0         2340
763565     114 2016-10-17 23:54:57        18.00            0         2340
763566     118 2016-10-17 23:55:15        18.73            0         2340
763567     122 2016-10-17 23:55:34        78.38            0         2340

[763568 rows x 5 columns]

In [6]:
avg_segment_time_week = df_travel_segment.groupby( ['day_of_week', 'minute_block', 'link_id']).aggregate(np.average)
avg_route_time_week   = df_trajectories.groupby( ['intersection_id', 'tollgate_id', 'day_of_week', 'minute_block',]).aggregate(np.average)
avg_route_time_whole  = df_trajectories.groupby( ['intersection_id', 'tollgate_id', pd.TimeGrouper( key="starting_time", freq="20min"), ] ).aggregate(np.average)

In [7]:
avg_segment_time_week

                                  travel_time
day_of_week minute_block link_id
0           0000         100         6.068421
                         101         7.728333
                         102         9.530000
                         103        10.768000
                         104        20.451111
                         105        10.803158
                         106         1.708000
                         107         3.425789
                         108         4.805000
                         109         8.953333
                         110        11.848421
                         111        25.277500
                         112        27.917778
                         113        23.828000
                         114        18.692273
                         115         9.196667
                         116        17.081667
                         117        27.662500
                         118        28.347727
                         119         1.067727
                         120         0.791250
                         121        11.795000
                         122        34.992439
                         123         5.554474
            0020         100         7.527000
                         101         7.858750
                         102         9.652857
                         103         6.627000
                         104        21.348333
                         105         9.604000
...                                       ...
6           2320         118        21.571429
                         119         0.888571
                         120         0.779545
                         121        18.377000
                         122        37.152000
                         123         5.517907
            2340         100         6.735000
                         101         8.060000
                         102        10.860000
                         103        10.503750
                         104        20.231429
                         105         9.841000
                         106         2.510000
                         107         4.657647
                         108         7.092059
                         109         8.275714
                         110        11.928529
                         111        19.336250
                         112        16.570000
                         113        24.485714
                         114        19.658462
                         115        13.425714
                         116        15.298571
                         117        24.753333
                         118        17.643846
                         119         0.690000
                         120         0.757619
                         121        15.880000
                         122        41.939259
                         123         5.210882

[12018 rows x 1 columns]