In [1]:
# Date: 22-5-2017

import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import ModelCheckpoint
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt
import datetime

Using TensorFlow backend.

In [5]:
# Note: caution: 十一黃金周

df_merged_volume = pd.read_csv("../data/preprocessed_input_traffic_time_and_weather_interpolate_20min_phase1and2_train.csv")

# change "Date" to datetime object
df_merged_volume['date'] = pd.to_datetime(df_merged_volume['date'])

# construct "time of day"
df_merged_volume['timeofday'] = df_merged_volume.date.apply( lambda d : d.hour+d.minute/60.)

In [7]:
# Select the phase 1 day

end_day = datetime.datetime(year=2016, month=10, day=18, hour=0, minute=0, second=0)

df_merged_volume = df_merged_volume[(df_merged_volume['date'] < end_day)]

In [8]:
# check any unreasonable rows
df_merged_volume.tail(30)

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
6522,52.276500,84.477500,99.415000,98.185000,191.138000,149.963750,2016-10-17 14:00:00,14,1014.566667,1019.666667,153.666667,0.833333,19.133333,90.333333,0.0,0,1,14.000000
6523,70.188333,100.532000,147.230000,104.857500,187.095714,150.720000,2016-10-17 14:20:00,14,1014.611111,1019.711111,176.444444,0.855556,19.055556,90.888889,0.0,0,1,14.333333
6524,48.458182,95.676250,120.550000,77.523333,175.006000,191.020000,2016-10-17 14:40:00,14,1014.655556,1019.755556,199.222222,0.877778,18.977778,91.444444,0.0,0,1,14.666667
6525,63.731667,107.575000,151.210000,95.880000,143.980000,126.445000,2016-10-17 15:00:00,15,1014.700000,1019.800000,222.000000,0.900000,18.900000,92.000000,0.0,0,1,15.000000
6526,90.638000,117.880000,138.695000,82.666667,134.580000,141.302222,2016-10-17 15:20:00,15,1014.622222,1019.711111,235.222222,0.966667,18.922222,92.000000,0.0,0,1,15.333333
6527,71.697500,131.028000,76.920000,126.845000,483.066667,156.159444,2016-10-17 15:40:00,15,1014.544444,1019.622222,248.444444,1.033333,18.944444,92.000000,0.0,0,1,15.666667
6528,53.860000,109.924444,134.990000,115.466667,180.284286,171.016667,2016-10-17 16:00:00,16,1014.466667,1019.533333,261.666667,1.100000,18.966667,92.000000,0.0,0,1,16.000000
6529,69.770000,111.731667,136.450000,100.271111,150.436667,311.180000,2016-10-17 16:20:00,16,1014.388889,1019.444444,274.888889,1.166667,18.988889,92.000000,0.0,0,1,16.333333
6530,61.900588,118.197778,109.502500,80.806667,170.890000,198.460000,2016-10-17 16:40:00,16,1014.311111,1019.355556,288.111111,1.233333,19.011111,92.000000,0.0,0,1,16.666667
6531,76.763333,125.567273,82.555000,99.529444,159.010000,160.238333,2016-10-17 17:00:00,17,1014.233333,1019.266667,301.333333,1.300000,19.033333,92.000000,0.0,0,1,17.000000
6532,58.044286,152.187500,130.780000,118.252222,170.135000,122.016667,2016-10-17 17:20:00,17,1014.155556,1019.177778,314.555556,1.366667,19.055556,92.000000,0.0,0,1,17.333333
6533,53.686667,125.555000,177.360000,102.548333,218.620000,147.878333,2016-10-17 17:40:00,17,1014.077778,1019.088889,327.777778,1.433333,19.077778,92.000000,0.0,0,1,17.666667
6534,65.400000,158.007143,137.915000,92.785417,267.105000,173.740000,2016-10-17 18:00:00,18,1014.000000,1019.000000,341.000000,1.500000,19.100000,92.000000,0.0,0,1,18.000000
6535,48.660000,115.047000,98.470000,83.022500,251.330000,350.113333,2016-10-17 18:20:00,18,1013.988889,1018.988889,338.888889,1.611111,19.122222,91.777778,0.0,0,1,18.333333
6536,60.415000,116.365000,142.190000,75.858000,235.555000,526.486667,2016-10-17 18:40:00,18,1013.977778,1018.977778,336.777778,1.722222,19.144444,91.555556,0.0,0,1,18.666667
6537,85.116000,107.770000,130.702500,121.795000,219.780000,101.730000,2016-10-17 19:00:00,19,1013.966667,1018.966667,334.666667,1.833333,19.166667,91.333333,0.0,0,1,19.000000
6538,67.144167,131.227500,114.872917,91.640000,204.005000,144.580000,2016-10-17 19:20:00,19,1013.955556,1018.955556,332.555556,1.944444,19.188889,91.111111,0.0,0,1,19.333333
6539,65.930000,86.107500,99.043333,95.705000,188.230000,187.430000,2016-10-17 19:40:00,19,1013.944444,1018.944444,330.444444,2.055556,19.211111,90.888889,0.0,0,1,19.666667
6540,52.660000,101.295556,135.786667,99.770000,182.810000,209.320000,2016-10-17 20:00:00,20,1013.933333,1018.933333,328.333333,2.166667,19.233333,90.666667,0.0,0,1,20.000000
6541,72.693333,137.584000,172.530000,95.901667,177.390000,201.905000,2016-10-17 20:20:00,20,1013.922222,1018.922222,326.222222,2.277778,19.255556,90.444444,0.0,0,1,20.333333
6542,42.643333,80.685000,89.990000,92.033333,171.970000,194.490000,2016-10-17 20:40:00,20,1013.911111,1018.911111,324.111111,2.388889,19.277778,90.222222,0.0,0,1,20.666667
6543,64.073333,112.610000,119.020000,46.390000,146.790000,195.005000,2016-10-17 21:00:00,21,1013.900000,1018.900000,322.000000,2.500000,19.300000,90.000000,0.0,0,1,21.000000
6544,53.825000,103.680000,123.460000,61.960000,121.610000,159.440000,2016-10-17 21:20:00,21,1013.893567,1018.893567,322.066277,2.501754,19.301754,89.992203,0.0,0,1,21.333333
6545,39.552500,100.025000,127.900000,79.840000,119.458333,168.043333,2016-10-17 21:40:00,21,1013.887135,1018.887135,322.132554,2.503509,19.303509,89.984405,0.0,0,1,21.666667
6546,69.050000,80.105000,132.340000,97.720000,117.306667,176.646667,2016-10-17 22:00:00,22,1013.880702,1018.880702,322.198830,2.505263,19.305263,89.976608,0.0,0,1,22.000000
6547,50.182500,71.970000,136.780000,115.600000,115.155000,185.250000,2016-10-17 22:20:00,22,1013.874269,1018.874269,322.265107,2.507018,19.307018,89.968811,0.0,0,1,22.333333
6548,55.830000,83.760000,123.700000,60.920000,154.742500,150.525000,2016-10-17 22:40:00,22,1013.867836,1018.867836,322.331384,2.508772,19.308772,89.961014,0.0,0,1,22.666667
6549,50.900000,103.685000,110.620000,60.490000,194.330000,149.609167,2016-10-17 23:00:00,23,1013.861404,1018.861404,322.397661,2.510526,19.310526,89.953216,0.0,0,1,23.000000
6550,79.214000,157.230000,97.540000,131.680000,159.780000,148.693333,2016-10-17 23:20:00,23,1013.854971,1018.854971,322.463938,2.512281,19.312281,89.945419,0.0,0,1,23.333333
6551,42.270000,113.943333,95.554000,98.187500,152.175000,147.777500,2016-10-17 23:40:00,23,1013.848538,1018.848538,322.530214,2.514035,19.314035,89.937622,0.0,0,1,23.666667

In [9]:
''' Cut some rows (proprecessing)'''
df_merged_volume = df_merged_volume[4:]  # Cut of NaN rows at the beginning
df_merged_volume = df_merged_volume.reset_index(drop=True)  # reindexing
df_merged_volume

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
0,56.870000,94.570000,176.700000,107.487500,214.870000,119.210588,2016-07-19 01:20:00,1,1000.722222,1005.577778,215.888889,3.522222,29.366667,73.888889,0.0,1,0,1.333333
1,77.740000,88.916667,167.517778,93.720000,160.635000,122.045882,2016-07-19 01:40:00,1,1000.677778,1005.522222,215.111111,3.577778,29.833333,72.111111,0.0,1,0,1.666667
2,60.190000,83.263333,158.335556,67.810000,163.597778,124.881176,2016-07-19 02:00:00,2,1000.633333,1005.466667,214.333333,3.633333,30.300000,70.333333,0.0,1,0,2.000000
3,42.640000,77.610000,149.153333,117.677500,166.560556,127.716471,2016-07-19 02:20:00,2,1000.588889,1005.411111,213.555556,3.688889,30.766667,68.555556,0.0,1,0,2.333333
4,40.173333,85.350000,139.971111,167.545000,169.523333,130.551765,2016-07-19 02:40:00,2,1000.544444,1005.355556,212.777778,3.744444,31.233333,66.777778,0.0,1,0,2.666667
5,41.046667,93.090000,130.788889,144.526667,172.486111,133.387059,2016-07-19 03:00:00,3,1000.500000,1005.300000,212.000000,3.800000,31.700000,65.000000,0.0,1,0,3.000000
6,41.920000,92.794000,121.606667,121.508333,175.448889,136.222353,2016-07-19 03:20:00,3,1000.411111,1005.211111,215.000000,3.588889,31.711111,64.888889,0.0,1,0,3.333333
7,39.430000,92.498000,112.424444,98.490000,178.411667,139.057647,2016-07-19 03:40:00,3,1000.322222,1005.122222,218.000000,3.377778,31.722222,64.777778,0.0,1,0,3.666667
8,48.130000,92.202000,103.242222,96.670000,181.374444,141.892941,2016-07-19 04:00:00,4,1000.233333,1005.033333,221.000000,3.166667,31.733333,64.666667,0.0,1,0,4.000000
9,62.106667,91.906000,94.060000,53.150000,184.337222,144.728235,2016-07-19 04:20:00,4,1000.144444,1004.944444,224.000000,2.955556,31.744444,64.555556,0.0,1,0,4.333333
10,46.115000,91.610000,85.033333,55.245000,187.300000,147.563529,2016-07-19 04:40:00,4,1000.055556,1004.855556,227.000000,2.744444,31.755556,64.444444,0.0,1,0,4.666667
11,49.556000,129.985000,76.006667,209.660000,180.570000,150.398824,2016-07-19 05:00:00,5,999.966667,1004.766667,230.000000,2.533333,31.766667,64.333333,0.0,1,0,5.000000
12,54.840000,168.360000,66.980000,188.420000,173.840000,153.234118,2016-07-19 05:20:00,5,999.877778,1004.677778,233.000000,2.322222,31.777778,64.222222,0.0,1,0,5.333333
13,58.084286,146.510000,87.830000,167.180000,167.110000,156.069412,2016-07-19 05:40:00,5,999.788889,1004.588889,236.000000,2.111111,31.788889,64.111111,0.0,1,0,5.666667
14,46.356000,124.660000,170.090000,145.940000,160.380000,158.904706,2016-07-19 06:00:00,6,999.700000,1004.500000,239.000000,1.900000,31.800000,64.000000,0.0,1,0,6.000000
15,48.588000,89.846000,135.196667,127.350000,147.470000,161.740000,2016-07-19 06:20:00,6,999.588889,1004.388889,236.666667,1.911111,31.766667,64.555556,0.0,1,0,6.333333
16,66.642500,180.016000,100.303333,97.200000,134.560000,223.810000,2016-07-19 06:40:00,6,999.477778,1004.277778,234.333333,1.922222,31.733333,65.111111,0.0,1,0,6.666667
17,64.681000,101.395000,65.410000,118.428000,149.743333,135.920000,2016-07-19 07:00:00,7,999.366667,1004.166667,232.000000,1.933333,31.700000,65.666667,0.0,1,0,7.000000
18,85.676000,124.288000,81.245000,82.630000,164.926667,236.120000,2016-07-19 07:20:00,7,999.255556,1004.055556,229.666667,1.944444,31.666667,66.222222,0.0,1,0,7.333333
19,58.968889,155.495000,97.080000,110.500000,180.110000,178.425000,2016-07-19 07:40:00,7,999.144444,1003.944444,227.333333,1.955556,31.633333,66.777778,0.0,1,0,7.666667
20,81.602857,137.375000,112.915000,125.760000,151.386667,120.730000,2016-07-19 08:00:00,8,999.033333,1003.833333,225.000000,1.966667,31.600000,67.333333,0.0,1,0,8.000000
21,80.207857,165.482857,128.750000,141.334000,129.100000,143.370000,2016-07-19 08:20:00,8,998.922222,1003.722222,222.666667,1.977778,31.566667,67.888889,0.0,1,0,8.333333
22,63.448462,136.680000,71.893333,176.077143,164.983333,142.452500,2016-07-19 08:40:00,8,998.811111,1003.611111,220.333333,1.988889,31.533333,68.444444,0.0,1,0,8.666667
23,78.051176,192.680000,177.106667,165.290000,200.866667,141.535000,2016-07-19 09:00:00,9,998.700000,1003.500000,218.000000,2.000000,31.500000,69.000000,0.0,1,0,9.000000
24,69.038333,159.780000,104.330000,127.382500,164.520000,140.617500,2016-07-19 09:20:00,9,998.866667,1003.666667,217.666667,1.855556,31.333333,69.888889,0.0,1,0,9.333333
25,69.657143,129.275000,118.503333,117.827500,182.718333,139.700000,2016-07-19 09:40:00,9,999.033333,1003.833333,217.333333,1.711111,31.166667,70.777778,0.0,1,0,9.666667
26,78.311538,99.037500,132.676667,98.921667,200.916667,139.700000,2016-07-19 10:00:00,10,999.200000,1004.000000,217.000000,1.566667,31.000000,71.666667,0.0,1,0,10.000000
27,59.411818,129.300000,170.595000,112.998333,203.876000,114.250000,2016-07-19 10:20:00,10,999.366667,1004.166667,216.666667,1.422222,30.833333,72.555556,0.0,1,0,10.333333
28,75.488889,121.102857,79.570000,98.150000,301.280000,130.085714,2016-07-19 10:40:00,10,999.533333,1004.333333,216.333333,1.277778,30.666667,73.444444,0.0,1,0,10.666667
29,72.435000,104.786000,54.460000,95.983333,42.950000,145.921429,2016-07-19 11:00:00,11,999.700000,1004.500000,216.000000,1.133333,30.500000,74.333333,0.0,1,0,11.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6518,52.276500,84.477500,99.415000,98.185000,191.138000,149.963750,2016-10-17 14:00:00,14,1014.566667,1019.666667,153.666667,0.833333,19.133333,90.333333,0.0,0,1,14.000000
6519,70.188333,100.532000,147.230000,104.857500,187.095714,150.720000,2016-10-17 14:20:00,14,1014.611111,1019.711111,176.444444,0.855556,19.055556,90.888889,0.0,0,1,14.333333
6520,48.458182,95.676250,120.550000,77.523333,175.006000,191.020000,2016-10-17 14:40:00,14,1014.655556,1019.755556,199.222222,0.877778,18.977778,91.444444,0.0,0,1,14.666667
6521,63.731667,107.575000,151.210000,95.880000,143.980000,126.445000,2016-10-17 15:00:00,15,1014.700000,1019.800000,222.000000,0.900000,18.900000,92.000000,0.0,0,1,15.000000
6522,90.638000,117.880000,138.695000,82.666667,134.580000,141.302222,2016-10-17 15:20:00,15,1014.622222,1019.711111,235.222222,0.966667,18.922222,92.000000,0.0,0,1,15.333333
6523,71.697500,131.028000,76.920000,126.845000,483.066667,156.159444,2016-10-17 15:40:00,15,1014.544444,1019.622222,248.444444,1.033333,18.944444,92.000000,0.0,0,1,15.666667
6524,53.860000,109.924444,134.990000,115.466667,180.284286,171.016667,2016-10-17 16:00:00,16,1014.466667,1019.533333,261.666667,1.100000,18.966667,92.000000,0.0,0,1,16.000000
6525,69.770000,111.731667,136.450000,100.271111,150.436667,311.180000,2016-10-17 16:20:00,16,1014.388889,1019.444444,274.888889,1.166667,18.988889,92.000000,0.0,0,1,16.333333
6526,61.900588,118.197778,109.502500,80.806667,170.890000,198.460000,2016-10-17 16:40:00,16,1014.311111,1019.355556,288.111111,1.233333,19.011111,92.000000,0.0,0,1,16.666667
6527,76.763333,125.567273,82.555000,99.529444,159.010000,160.238333,2016-10-17 17:00:00,17,1014.233333,1019.266667,301.333333,1.300000,19.033333,92.000000,0.0,0,1,17.000000
6528,58.044286,152.187500,130.780000,118.252222,170.135000,122.016667,2016-10-17 17:20:00,17,1014.155556,1019.177778,314.555556,1.366667,19.055556,92.000000,0.0,0,1,17.333333
6529,53.686667,125.555000,177.360000,102.548333,218.620000,147.878333,2016-10-17 17:40:00,17,1014.077778,1019.088889,327.777778,1.433333,19.077778,92.000000,0.0,0,1,17.666667
6530,65.400000,158.007143,137.915000,92.785417,267.105000,173.740000,2016-10-17 18:00:00,18,1014.000000,1019.000000,341.000000,1.500000,19.100000,92.000000,0.0,0,1,18.000000
6531,48.660000,115.047000,98.470000,83.022500,251.330000,350.113333,2016-10-17 18:20:00,18,1013.988889,1018.988889,338.888889,1.611111,19.122222,91.777778,0.0,0,1,18.333333
6532,60.415000,116.365000,142.190000,75.858000,235.555000,526.486667,2016-10-17 18:40:00,18,1013.977778,1018.977778,336.777778,1.722222,19.144444,91.555556,0.0,0,1,18.666667
6533,85.116000,107.770000,130.702500,121.795000,219.780000,101.730000,2016-10-17 19:00:00,19,1013.966667,1018.966667,334.666667,1.833333,19.166667,91.333333,0.0,0,1,19.000000
6534,67.144167,131.227500,114.872917,91.640000,204.005000,144.580000,2016-10-17 19:20:00,19,1013.955556,1018.955556,332.555556,1.944444,19.188889,91.111111,0.0,0,1,19.333333
6535,65.930000,86.107500,99.043333,95.705000,188.230000,187.430000,2016-10-17 19:40:00,19,1013.944444,1018.944444,330.444444,2.055556,19.211111,90.888889,0.0,0,1,19.666667
6536,52.660000,101.295556,135.786667,99.770000,182.810000,209.320000,2016-10-17 20:00:00,20,1013.933333,1018.933333,328.333333,2.166667,19.233333,90.666667,0.0,0,1,20.000000
6537,72.693333,137.584000,172.530000,95.901667,177.390000,201.905000,2016-10-17 20:20:00,20,1013.922222,1018.922222,326.222222,2.277778,19.255556,90.444444,0.0,0,1,20.333333
6538,42.643333,80.685000,89.990000,92.033333,171.970000,194.490000,2016-10-17 20:40:00,20,1013.911111,1018.911111,324.111111,2.388889,19.277778,90.222222,0.0,0,1,20.666667
6539,64.073333,112.610000,119.020000,46.390000,146.790000,195.005000,2016-10-17 21:00:00,21,1013.900000,1018.900000,322.000000,2.500000,19.300000,90.000000,0.0,0,1,21.000000
6540,53.825000,103.680000,123.460000,61.960000,121.610000,159.440000,2016-10-17 21:20:00,21,1013.893567,1018.893567,322.066277,2.501754,19.301754,89.992203,0.0,0,1,21.333333
6541,39.552500,100.025000,127.900000,79.840000,119.458333,168.043333,2016-10-17 21:40:00,21,1013.887135,1018.887135,322.132554,2.503509,19.303509,89.984405,0.0,0,1,21.666667
6542,69.050000,80.105000,132.340000,97.720000,117.306667,176.646667,2016-10-17 22:00:00,22,1013.880702,1018.880702,322.198830,2.505263,19.305263,89.976608,0.0,0,1,22.000000
6543,50.182500,71.970000,136.780000,115.600000,115.155000,185.250000,2016-10-17 22:20:00,22,1013.874269,1018.874269,322.265107,2.507018,19.307018,89.968811,0.0,0,1,22.333333
6544,55.830000,83.760000,123.700000,60.920000,154.742500,150.525000,2016-10-17 22:40:00,22,1013.867836,1018.867836,322.331384,2.508772,19.308772,89.961014,0.0,0,1,22.666667
6545,50.900000,103.685000,110.620000,60.490000,194.330000,149.609167,2016-10-17 23:00:00,23,1013.861404,1018.861404,322.397661,2.510526,19.310526,89.953216,0.0,0,1,23.000000
6546,79.214000,157.230000,97.540000,131.680000,159.780000,148.693333,2016-10-17 23:20:00,23,1013.854971,1018.854971,322.463938,2.512281,19.312281,89.945419,0.0,0,1,23.333333
6547,42.270000,113.943333,95.554000,98.187500,152.175000,147.777500,2016-10-17 23:40:00,23,1013.848538,1018.848538,322.530214,2.514035,19.314035,89.937622,0.0,0,1,23.666667

In [10]:
''' Make the dataset stationary '''

station_cols = 6  # select the first 6 columns for stationary

df_merged_volume_copy = df_merged_volume.copy()

for i in range(1, len(df_merged_volume_copy)):
    df_merged_volume_copy.loc[i, df_merged_volume_copy.columns[0:station_cols]] = df_merged_volume.loc[i, df_merged_volume.columns[0:station_cols]] - df_merged_volume.loc[i-1, df_merged_volume.columns[0:station_cols]]

In [11]:
# Check Stationary dataframe

df_merged_volume_copy.tail()

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
6543,-18.8675,-8.135000,4.440,17.8800,-2.151667,8.603333,2016-10-17 22:20:00,22,1013.874269,1018.874269,322.265107,2.507018,19.307018,89.968811,0.0,0,1,22.333333
6544,5.6475,11.790000,-13.080,-54.6800,39.587500,-34.725000,2016-10-17 22:40:00,22,1013.867836,1018.867836,322.331384,2.508772,19.308772,89.961014,0.0,0,1,22.666667
6545,-4.9300,19.925000,-13.080,-0.4300,39.587500,-0.915833,2016-10-17 23:00:00,23,1013.861404,1018.861404,322.397661,2.510526,19.310526,89.953216,0.0,0,1,23.000000
6546,28.3140,53.545000,-13.080,71.1900,-34.550000,-0.915833,2016-10-17 23:20:00,23,1013.854971,1018.854971,322.463938,2.512281,19.312281,89.945419,0.0,0,1,23.333333
6547,-36.9440,-43.286667,-1.986,-33.4925,-7.605000,-0.915833,2016-10-17 23:40:00,23,1013.848538,1018.848538,322.530214,2.514035,19.314035,89.937622,0.0,0,1,23.666667

In [12]:
## Hidden the selecting time
# select the time for training: 6:20-10:00 (5 + 6 timestamp) and 15:20-19:00 (5 + 6 timestamp)
# sel_rows = df_merged_volume_copy[ ((df_merged_volume_copy.timeofday>= 6.3) & (df_merged_volume_copy.timeofday<10)) |
#                             ((df_merged_volume_copy.timeofday>=15.3) & (df_merged_volume_copy.timeofday<19))]

## This time, training all time (24hrs) except the first non-stationary row
sel_rows = df_merged_volume_copy[1:]

In [13]:
# Create one-hot for hour

# for i in range(24):
#     sel_rows['{}:00'.format(i)] = np.where(sel_rows.hour == i, 1, 0)

In [14]:
# Check all the columns
for idx, i in enumerate(sel_rows.columns):
    print(idx, i)

0 ('A', 2)
1 ('A', 3)
2 ('B', 1)
3 ('B', 3)
4 ('C', 1)
5 ('C', 3)
6 date
7 hour
8 pressure
9 sea_pressure
10 wind_direction
11 wind_speed
12 temperature
13 rel_humidity
14 precipitation
15 dayofweek
16 is_holiday
17 timeofday

In [15]:
# select using columns

using_cols = [
#                 "(1, 0, 'cargocar')",
#                 "(1, 0, 'etc')",
#                 "(1, 0, 'motorcycle')",
#                 "(1, 0, 'privatecar')",
#                 "(1, 0, 'tot')",
#                 "(1, 0, 'unknowncar')",
#                 "(1, 1, 'cargocar')",
#                 "(1, 1, 'etc')",
#                 "(1, 1, 'motorcycle')",
#                 "(1, 1, 'privatecar')",
#                 "(1, 1, 'tot')",
#                 "(1, 1, 'unknowncar')",
#                 "(2, 0, 'cargocar')",
#                 "(2, 0, 'etc')",
#                 "(2, 0, 'motorcycle')",
#                 "(2, 0, 'privatecar')",
#                 "(2, 0, 'tot')",
#                 "(2, 0, 'unknowncar')",
#                 "(3, 0, 'cargocar')",
#                 "(3, 0, 'etc')",
#                 "(3, 0, 'motorcycle')",
#                 "(3, 0, 'privatecar')",
#                 "(3, 0, 'tot')",
#                 "(3, 0, 'unknowncar')",
#                 "(3, 1, 'cargocar')",
#                 "(3, 1, 'etc')",
#                 "(3, 1, 'motorcycle')",
#                 "(3, 1, 'privatecar')",
#                 "(3, 1, 'tot')",
#                 "(3, 1, 'unknowncar')",
                "('A', 2)",
#                 "('A', 3)",
#                 "('B', 1)",
#                 "('B', 3)",
#                 "('C', 1)",
#                 "('C', 3)",
#                 'date',  # <== Notice this
                'hour',
                'pressure',
#                 'sea_pressure',
#                 'wind_direction',
#                 'wind_speed',
                'temperature',
#                 'rel_humidity',
                'precipitation',
                'dayofweek',
                'is_holiday',
                'timeofday',
#                 '0:00',
#                 '1:00',
#                 '2:00',
#                 '3:00',
#                 '4:00',
#                 '5:00',
#                 '6:00',
#                 '7:00',
#                 '8:00',
#                 '9:00',
#                 '10:00',
#                 '11:00',
#                 '12:00',
#                 '13:00',
#                 '14:00',
#                 '15:00',
#                 '16:00',
#                 '17:00',
#                 '18:00',
#                 '19:00',
#                 '20:00',
#                 '21:00',
#                 '22:00',
#                 '23:00',
              ]

sel_rows = sel_rows[using_cols]

In [16]:
# split to train and valid set
train_rows = sel_rows[: -24*3*7]
valid_rows = sel_rows[-24*3*7:] # reserve 7 days for validation

# get numpy array from panda dataframe
train_arr = train_rows.values
valid_arr = valid_rows.values

# np.shape(train_arr)
# Out:
# (726, 17)

In [17]:
#scale feature array to range -1 to 1

scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = scaler.fit(train_arr)
train_scaled_arr = scaler.transform(train_arr)

valid_scaled_arr = scaler.transform(valid_arr)

In [18]:
# sample subsequence from the time series
train_seqs = []
len_seqs = len(train_scaled_arr) - 6 + 1  # 6 is window size
for i in range(len_seqs):
    train_seqs.append(train_scaled_arr[i: i+6])  # append 6 timestamps each time (5 timestamps for x, 1 timestamp for y)
train_seqs = np.stack(train_seqs)

valid_seqs = []
len_v_seqs = len(valid_scaled_arr) - 6 + 1  # 6 is window size
for i in range(len_v_seqs):
    valid_seqs.append(valid_scaled_arr[i: i+6])
valid_seqs = np.stack(valid_seqs)

In [19]:
# checking
train_seqs[:,:,:].shape

(6038, 6, 8)

In [20]:
#keras
#https://keras.io/getting-started/sequential-model-guide/#examples
input_dim = len(using_cols)  # The features
output_dim = 1  # 
timesteps = 5 # use 5 timesteps to predict the 6th

x_train, y_train = train_seqs[:, 0:-1], train_seqs[:, -1, 0:output_dim]  # 0:output_dim is for deciding the output features
x_valid , y_valid  =  valid_seqs[:, 0:-1],  valid_seqs[:, -1, 0:output_dim]  # 0:output_dim is for deciding the output features

In [21]:
y_train.shape

(6038, 1)

In [22]:
num_epochs = 120
loss_fuc = 'mean_squared_error'

# construct the callback
filepath="best_epoch_T.M._A-2_phase1.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

model = Sequential()
model.add(LSTM(128, input_shape=(timesteps, input_dim), return_sequences=True))
model.add(LSTM(128))
model.add(Dense(output_dim))
model.compile(loss=loss_fuc, optimizer='adam')

In [ ]:
## Start Training
model.summary()
history_w_model = model.fit(x_train, y_train, callbacks=callbacks_list, epochs=num_epochs, batch_size=64, validation_data=(x_valid, y_valid))

plt.plot(history_w_model.history['loss'], label='loss')
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.plot(history_w_model.history['val_loss'], label='Val_loss')
plt.show()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_1 (LSTM)                (None, 5, 128)            70144
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129
=================================================================
Total params: 201,857
Trainable params: 201,857
Non-trainable params: 0
_________________________________________________________________
Train on 6038 samples, validate on 499 samples
Epoch 1/120
6016/6038 [============================>.] - ETA: 0s - loss: 0.0056Epoch 00000: val_loss improved from inf to 0.00196, saving model to best_epoch_T.M._A-2_phase1.hdf5
6038/6038 [==============================] - 6s - loss: 0.0057 - val_loss: 0.0020
Epoch 2/120
6016/6038 [============================>.] - ETA: 0s - loss: 0.0033Epoch 00001: val_loss did not improve
6038/6038 [==============================] - 5s - loss: 0.0033 - val_loss: 0.0021
Epoch 3/120
6016/6038 [============================>.] - ETA: 0s - loss: 0.0033Epoch 00002: val_loss did not improve
6038/6038 [==============================] - 5s - loss: 0.0033 - val_loss: 0.0020
Epoch 4/120
6016/6038 [============================>.] - ETA: 0s - loss: 0.0032Epoch 00003: val_loss improved from 0.00196 to 0.00194, saving model to best_epoch_T.M._A-2_phase1.hdf5
6038/6038 [==============================] - 5s - loss: 0.0032 - val_loss: 0.0019
Epoch 5/120
1408/6038 [=====>........................] - ETA: 4s - loss: 0.0040

In [19]:
# Notes: last best model: 0.00175
# load weights into the model
model.load_weights("best_epoch_T.M._A-2.hdf5")
print("Loaded model from disk")

model.compile(loss='mean_squared_error', optimizer='adam')

Loaded model from disk

In [20]:
''' === Prediction ===
Procedure:
1. Load CSV
2. to_datetime
3. create timeofday column
4. select the time for training: 6:00-8:00 (6 timestamps) and 15:00-17:00 (6 timestamps)
5. change it to stationary
6. Use using_cols to select the features
7. change to np array
8. MinMaxScaler
9. make the sequences tensor as input
10. make a forloop for prediction

'''
# 1. Load CSV - Vol + Route + Weather (Only Weather is 24-hour data)
df_pred = pd.read_csv('../data/preprocessed_input_interpolate_20min_phase1and2_train.csv')

# 2. to_datetime
df_pred['date'] = pd.to_datetime(df_pred['date'])

# 3. create timeofday column
df_pred['timeofday'] = df_pred.date.apply( lambda d : d.hour+d.minute/60.)

In [21]:
# Select the checking days (No need to real final test)

start_day = datetime.datetime(year=2016, month=10, day=18, hour=1, minute=0, second=0)
end_day = datetime.datetime(year=2016, month=10, day=24, hour=23, minute=0, second=0)

df_pred_sel = df_pred[(df_pred['date'] > start_day) & (df_pred['date'] < end_day)]

In [22]:
# 4. select the time for training

df_pred_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 6) & (df_pred_sel.timeofday<8)) |
                            ((df_pred_sel.timeofday>=15) & (df_pred_sel.timeofday<17))]

df_feedin_weather_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 8) & (df_pred_sel.timeofday<10)) |
                            ((df_pred_sel.timeofday>=17) & (df_pred_sel.timeofday<19))]

In [23]:
# Checking
df_pred_sel_time.iloc[12]

(1, 0, 'cargocar')                        0
(1, 0, 'etc')                             1
(1, 0, 'motorcycle')                      0
(1, 0, 'privatecar')                      0
(1, 0, 'tot')                            12
(1, 0, 'unknowncar')                     12
(1, 1, 'cargocar')                       28
(1, 1, 'etc')                             6
(1, 1, 'motorcycle')                     20
(1, 1, 'privatecar')                      0
(1, 1, 'tot')                            48
(1, 1, 'unknowncar')                      0
(2, 0, 'cargocar')                        0
(2, 0, 'etc')                             6
(2, 0, 'motorcycle')                      0
(2, 0, 'privatecar')                      0
(2, 0, 'tot')                            26
(2, 0, 'unknowncar')                     26
(3, 0, 'cargocar')                        0
(3, 0, 'etc')                             3
(3, 0, 'motorcycle')                      0
(3, 0, 'privatecar')                      0
(3, 0, 'tot')                            24
(3, 0, 'unknowncar')                     24
(3, 1, 'cargocar')                       14
(3, 1, 'etc')                             2
(3, 1, 'motorcycle')                      6
(3, 1, 'privatecar')                      1
(3, 1, 'tot')                            21
(3, 1, 'unknowncar')                      0
('A', 2)                              40.01
('A', 3)                              89.51
('B', 1)                            111.035
('B', 3)                             102.83
('C', 1)                            160.492
('C', 3)                             126.74
date                    2016-10-19 06:00:00
hour                                      6
pressure                            1013.26
sea_pressure                        1018.26
wind_direction                      328.561
wind_speed                          2.67368
temperature                         19.4737
rel_humidity                        89.2281
precipitation                             0
dayofweek                                 2
is_holiday                                0
timeofday                                 6
Name: 2106, dtype: object

In [24]:
# 5. change it to stationary
df_pred_sel_time = df_pred_sel_time.reset_index(drop=True)

df_pred_sel_time_copy = df_pred_sel_time.copy()

for i in range(len(df_pred_sel_time_copy)//6):  # make the loop for 14 time slots (2 different time slot x 7days)
    for t in range(5):  #  Do the "difference" 5 times every loop
        start_idx = i*6 + t + 1  # Add 1 is for starting it from index 1 in every 6-space time slot
        df_pred_sel_time_copy.loc[start_idx, df_pred_sel_time_copy.columns[0:36]] = df_pred_sel_time.loc[start_idx, df_pred_sel_time.columns[0:36]] - df_pred_sel_time.loc[start_idx-1, df_pred_sel_time.columns[0:36]]

In [25]:
# Create one-hot for it
# for i in range(24):
#     df_pred_sel_time_copy['{}:00'.format(i)] = np.where(df_pred_sel_time_copy.hour == i, 1, 0)
#     df_feedin_weather_sel_time['{}:00'.format(i)] = np.where(df_feedin_weather_sel_time.hour == i, 1, 0)

In [26]:
# 6. Use using_cols to select the features

sel_rows_pred = df_pred_sel_time_copy[ using_cols ]

sel_rows_feedin_weather = df_feedin_weather_sel_time[using_cols[output_dim:]]

In [27]:
sel_rows_pred

,"('A', 2)",hour,pressure,temperature,precipitation,dayofweek,is_holiday,timeofday
0,41.097143,6,1013.726316,19.347368,0.0,1,0,6.000000
1,2.584524,6,1013.719883,19.349123,0.0,1,0,6.333333
2,24.342619,6,1013.713450,19.350877,0.0,1,0,6.666667
3,-15.415952,7,1013.707018,19.352632,0.0,1,0,7.000000
4,3.557222,7,1013.700585,19.354386,0.0,1,0,7.333333
5,7.433016,7,1013.694152,19.356140,0.0,1,0,7.666667
6,99.960667,15,1013.552632,19.394737,0.0,1,0,15.000000
7,-11.600111,15,1013.546199,19.396491,0.0,1,0,15.333333
8,-13.474556,15,1013.539766,19.398246,0.0,1,0,15.666667
9,-11.583273,16,1013.533333,19.400000,0.0,1,0,16.000000
10,8.059273,16,1013.526901,19.401754,0.0,1,0,16.333333
11,27.898909,16,1013.520468,19.403509,0.0,1,0,16.666667
12,40.010000,6,1013.263158,19.473684,0.0,2,0,6.000000
13,16.997273,6,1013.256725,19.475439,0.0,2,0,6.333333
14,-19.595273,6,1013.250292,19.477193,0.0,2,0,6.666667
15,32.172000,7,1013.243860,19.478947,0.0,2,0,7.000000
16,30.530000,7,1013.237427,19.480702,0.0,2,0,7.333333
17,-41.821857,7,1013.230994,19.482456,0.0,2,0,7.666667
18,64.462857,15,1013.089474,19.521053,0.0,2,0,15.000000
19,-2.155079,15,1013.083041,19.522807,0.0,2,0,15.333333
20,-4.977778,15,1013.076608,19.524561,0.0,2,0,15.666667
21,10.254000,16,1013.070175,19.526316,0.0,2,0,16.000000
22,-12.394000,16,1013.063743,19.528070,0.0,2,0,16.333333
23,17.286364,16,1013.057310,19.529825,0.0,2,0,16.666667
24,63.584000,6,1012.800000,19.600000,0.0,3,0,6.000000
25,-13.790667,6,1012.793567,19.601754,0.0,3,0,6.333333
26,11.091667,6,1012.787135,19.603509,0.0,3,0,6.666667
27,13.188750,7,1012.780702,19.605263,0.0,3,0,7.000000
28,-11.085179,7,1012.774269,19.607018,0.0,3,0,7.333333
29,12.805000,7,1012.767836,19.608772,0.0,3,0,7.666667
...,...,...,...,...,...,...,...,...
54,63.869000,15,1011.700000,19.900000,0.0,5,0,15.000000
55,4.286000,15,1011.693567,19.901754,0.0,5,0,15.333333
56,-9.359286,15,1011.687135,19.903509,0.0,5,0,15.666667
57,10.182857,16,1011.680702,19.905263,0.0,5,0,16.000000
58,13.088701,16,1011.674269,19.907018,0.0,5,0,16.333333
59,-16.080350,16,1011.667836,19.908772,0.0,5,0,16.666667
60,71.920000,6,1011.410526,19.978947,0.0,6,1,6.000000
61,-2.940000,6,1011.404094,19.980702,0.0,6,1,6.333333
62,8.085714,6,1011.397661,19.982456,0.0,6,1,6.666667
63,-33.685714,7,1011.391228,19.984211,0.0,6,1,7.000000
64,6.156667,7,1011.384795,19.985965,0.0,6,1,7.333333
65,16.593333,7,1011.378363,19.987719,0.0,6,1,7.666667
66,94.766364,15,1011.236842,20.026316,0.0,6,1,15.000000
67,-15.377792,15,1011.230409,20.028070,0.0,6,1,15.333333
68,13.116429,15,1011.223977,20.029825,0.0,6,1,15.666667
69,-21.194231,16,1011.217544,20.031579,0.0,6,1,16.000000
70,3.882564,16,1011.211111,20.033333,0.0,6,1,16.333333
71,-3.626905,16,1011.204678,20.035088,0.0,6,1,16.666667
72,41.188333,6,1010.947368,20.105263,0.0,0,1,6.000000
73,8.927381,6,1010.940936,20.107018,0.0,0,1,6.333333
74,-12.947714,6,1010.934503,20.108772,0.0,0,1,6.666667
75,38.515750,7,1010.928070,20.110526,0.0,0,1,7.000000
76,-21.650893,7,1010.921637,20.112281,0.0,0,1,7.333333
77,24.245143,7,1010.915205,20.114035,0.0,0,1,7.666667
78,95.172222,15,1010.773684,20.152632,0.0,0,1,15.000000
79,-43.298586,15,1010.767251,20.154386,0.0,0,1,15.333333
80,-7.185303,15,1010.760819,20.156140,0.0,0,1,15.666667
81,42.616333,16,1010.754386,20.157895,0.0,0,1,16.000000
82,-19.589667,16,1010.747953,20.159649,0.0,0,1,16.333333
83,-8.917222,16,1010.741520,20.161404,0.0,0,1,16.666667

In [28]:
# 7. change to np array
pred_arr = sel_rows_pred.values

feedin_weather_arr = sel_rows_feedin_weather.values

# 8. MinMaxScaler
pred_arr_scaled = scaler.transform(pred_arr)

# add some dummy cells in front of the weather_array for transform
temp_arr = np.zeros((84,output_dim))
feedin_weather_arr = np.concatenate([temp_arr, feedin_weather_arr], axis=1)

feedin_weather_arr_scaled = scaler.transform(feedin_weather_arr)

# Now pred_arr_scaled is (84 x features)

In [29]:
# 9. make the sequences tensor as input
# Put into the model to get the prediction

ans_arr = []  # For holding the output answer
    
for i in range(len(pred_arr_scaled)//6):  # make the loop for 14 time slots (2 different time slot x 7days)
    # creating pre_seq
    pred_seq = []
    for t in range(5):  #  Do the "difference" 5 times every loop
        k = i*6 + t + 1  # Add 1 is for starting it from index 1 in every 6-space time slot, to ignore the first index which is non-stationary
        pred_seq.append(pred_arr_scaled[k])  # creating a sequence for a time slot
    
    # creating feedin_weather_seq
    feedin_weather_seq = []
    for t in range(6):  #  Do 6 times every loop
        k = i*6 + t  #
        feedin_weather_seq.append(feedin_weather_arr_scaled[k])


    pred_seq = np.stack(pred_seq)  # change back to the numpy array (2D)
    pred_seq = pred_seq.reshape(1, pred_seq.shape[0], pred_seq.shape[1])  # change to numpy 3D as input

    feedin_weather_seq = np.stack(feedin_weather_seq)  # change back to the numpy array (2D)
    feedin_weather_seq = feedin_weather_seq.reshape(1, feedin_weather_seq.shape[0], feedin_weather_seq.shape[1])  # change to numpy 3D as input

    for q in range(6):
        # predict next timestamp
        output_pred = model.predict(pred_seq)  # get one prediction output (size (1 x output feature(s)))
        ans_arr.append(output_pred)

        # update the input seq
        for j in range(1,5):
            pred_seq[0][j-1] = pred_seq[0][j]
        pred_seq[0][4] = feedin_weather_seq[0][q]
        pred_seq[0][4][0:output_dim] = output_pred[0]

In [30]:
# 10. Backward to the non-stationary, correct scale output

#  Helper functions

def backward_scaler(nn_output):
    tmp = np.zeros(14)
    tmp[0:output_dim] = nn_output
    tmp = scaler.inverse_transform(tmp)
    return tmp[0:output_dim]

def decode(last_timestamp_values, nn_output):
    tmp = np.zeros(input_dim)
    tmp[0:output_dim] = nn_output
    tmp = scaler.inverse_transform(tmp)
    return last_timestamp_values + tmp[0:output_dim]

# create the non-stationary 6:40 and 16:40 for decoding
df_non_station_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 7.5) & (df_pred_sel.timeofday<8)) |
                            ((df_pred_sel.timeofday>=16.5) & (df_pred_sel.timeofday<17))]

In [31]:
''' Output the non-stationary Answers (allAns)'''

tmp = df_non_station_sel_time[using_cols[0:output_dim]].values
allAns = []
for i in range(len(tmp)):
    seed = tmp[i]  # non-stationary for reconstructing a sequence
    segmentAns = []
    for timestep in range(6):
        seed = decode(seed, ans_arr[i*6+timestep])
        segmentAns.append(seed)
    allAns.append(segmentAns)

# Change back to np array for easy visualize
allAns = np.array(allAns)

/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)

In [32]:
# Checking
for i in allAns:
    print(i)

[[ 62.33660007]
 [ 63.00264395]
 [ 63.04903354]
 [ 64.32125438]
 [ 65.18828462]
 [ 65.62258279]]
[[ 81.48209208]
 [ 81.59064396]
 [ 81.64770942]
 [ 83.84267302]
 [ 84.38395697]
 [ 83.10922757]]
[[ 64.8352109 ]
 [ 67.09188251]
 [ 70.49424067]
 [ 70.38115485]
 [ 70.10855574]
 [ 71.86516543]]
[[ 64.81171441]
 [ 65.89705088]
 [ 65.67506747]
 [ 66.0307542 ]
 [ 66.9743705 ]
 [ 66.55919942]]
[[ 72.76970426]
 [ 74.7365565 ]
 [ 75.84299862]
 [ 77.02227888]
 [ 78.68952555]
 [ 79.66817911]]
[[ 63.7102102 ]
 [ 63.90416898]
 [ 64.04535417]
 [ 64.18816724]
 [ 64.32575596]
 [ 64.35160777]]
[[ 66.88988841]
 [ 67.70081359]
 [ 68.71446656]
 [ 70.68938248]
 [ 72.44171425]
 [ 73.30999379]]
[[ 84.4986984 ]
 [ 83.27206717]
 [ 84.5002974 ]
 [ 84.7491498 ]
 [ 84.13193235]
 [ 84.0447601 ]]
[[ 77.08714304]
 [ 76.13679706]
 [ 76.27169788]
 [ 78.32471417]
 [ 80.46934601]
 [ 81.35401791]]
[[ 68.60753936]
 [ 67.94112588]
 [ 68.62556858]
 [ 68.51308848]
 [ 68.12506135]
 [ 67.70453342]]
[[ 63.87021412]
 [ 63.97181912]
 [ 63.69255707]
 [ 65.57996499]
 [ 67.29652126]
 [ 68.22711452]]
[[ 74.00019834]
 [ 73.26948361]
 [ 72.00446471]
 [ 71.22835864]
 [ 70.71748338]
 [ 70.01932624]]
[[ 68.812613  ]
 [ 70.78077133]
 [ 70.45096929]
 [ 71.72453408]
 [ 72.2736167 ]
 [ 72.29789741]]
[[ 60.87375474]
 [ 65.43050673]
 [ 66.30855355]
 [ 63.00817398]
 [ 64.28879923]
 [ 65.31933672]]

In [33]:
# 11. Output the CSV file

# create the datetime objects
import datetime

pred_start_date = 18


start_8am = datetime.datetime(year=2016, month=10, day=pred_start_date, hour=8, minute=0, second=0)
start_5pm = datetime.datetime(year=2016, month=10, day=pred_start_date, hour=17, minute=0, second=0)
add_1_day = datetime.timedelta(days=1)
add_20_min = datetime.timedelta(minutes=20)

'''
allAns[x,y,z]
[x]: Segment (AM & PM, total 14)
[y]: timestamp (6 [20mins])
[z]: 3 features
'''
# allAns[0,:,1]

'\nallAns[x,y,z]\n[x]: Segment (AM & PM, total 14)\n[y]: timestamp (6 [20mins])\n[z]: 3 features\n'

In [34]:
# 11.a [FOR TRAFFIC TIME] Output the CSV file

route = 'A'
checkpoint = '2'
vol_or_traj = 0  # select the output cell

with open('{}-{}_checking_A-2_single.csv'.format(route, checkpoint), 'w') as f:
    for day in range(7):
        for am_pm in range(2):
            if am_pm == 0:
                ref_time = start_8am
            else:
                ref_time = start_5pm
            for timestep in range(6):
                start_timestamp = ref_time + day*add_1_day + timestep*add_20_min
                end_timestamp = start_timestamp + add_20_min
                start_timestr = start_timestamp.strftime("%Y-%m-%d %H:%M:00")
                end_timestr = end_timestamp.strftime("%Y-%m-%d %H:%M:00")
                f.write('{},{},"[{},{})",{}\n'.format(route,
                                                      checkpoint,
                                                      start_timestr,
                                                      end_timestr,
                                                      allAns[day*2+am_pm, timestep, vol_or_traj ]))

In [364]:
# 11.b [FOR VOLUME] Output the CSV file

checkpoint = '2'
direction = '0'
vol_or_traj = 1  # select the output cell

with open('{}-{}.csv'.format(checkpoint, direction), 'w') as f:
    for day in range(7):
        for am_pm in range(2):
            if am_pm == 0:
                ref_time = start_8am
            else:
                ref_time = start_5pm
            for timestep in range(6):
                start_timestamp = ref_time + day*add_1_day + timestep*add_20_min
                end_timestamp = start_timestamp + add_20_min
                start_timestr = start_timestamp.strftime("%Y-%m-%d %H:%M:00")
                end_timestr = end_timestamp.strftime("%Y-%m-%d %H:%M:00")
                f.write('{},"[{},{})",{},{}\n'.format(checkpoint,
                                                  start_timestr,
                                                  end_timestr,
                                                  direction,
                                                  allAns[day*2+am_pm, timestep, vol_or_traj ]))