In [1]:
# Date: 22-5-2017

import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import ModelCheckpoint
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold

import matplotlib.pyplot as plt

Using TensorFlow backend.

In [2]:
# Note: caution: 十一黃金周

df_merged_volume = pd.read_csv("../data/preprocessed_input_traffic_time_and_weather_interpolate_20min_phase1and2_train.csv")

# change "Date" to datetime object
df_merged_volume['date'] = pd.to_datetime(df_merged_volume['date'])

# construct "time of day"
df_merged_volume['timeofday'] = df_merged_volume.date.apply( lambda d : d.hour+d.minute/60.)

In [3]:
# check any unreasonable rows
df_merged_volume.tail(30)

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
7027,49.277500,93.632500,121.066667,95.150000,201.725333,158.030000,2016-10-24 14:20:00,14,1010.786550,1015.786550,354.077973,3.349123,20.149123,86.226121,0.0,0,1,14.333333
7028,69.829474,96.445714,133.770000,74.277500,171.234000,125.450000,2016-10-24 14:40:00,14,1010.780117,1015.780117,354.144250,3.350877,20.150877,86.218324,0.0,0,1,14.666667
7029,95.172222,98.460000,123.783750,127.515000,168.852500,183.315000,2016-10-24 15:00:00,15,1010.773684,1015.773684,354.210526,3.352632,20.152632,86.210526,0.0,0,1,15.000000
7030,51.873636,106.870833,104.528000,76.680000,202.636667,144.675000,2016-10-24 15:20:00,15,1010.767251,1015.767251,354.276803,3.354386,20.154386,86.202729,0.0,0,1,15.333333
7031,44.688333,94.068000,102.053333,98.000000,175.865000,203.965000,2016-10-24 15:40:00,15,1010.760819,1015.760819,354.343080,3.356140,20.156140,86.194932,0.0,0,1,15.666667
7032,87.304667,111.742500,140.980000,65.323333,181.693333,159.366667,2016-10-24 16:00:00,16,1010.754386,1015.754386,354.409357,3.357895,20.157895,86.187135,0.0,0,1,16.000000
7033,67.715000,107.980000,111.556000,82.300000,188.636667,159.588333,2016-10-24 16:20:00,16,1010.747953,1015.747953,354.475634,3.359649,20.159649,86.179337,0.0,0,1,16.333333
7034,58.797778,147.760000,121.080000,109.508750,159.583333,159.810000,2016-10-24 16:40:00,16,1010.741520,1015.741520,354.541910,3.361404,20.161404,86.171540,0.0,0,1,16.666667
7035,85.030000,121.974167,114.141667,110.457778,190.150000,161.790000,2016-10-24 17:00:00,17,1010.735088,1015.735088,354.608187,3.363158,20.163158,86.163743,0.0,0,1,17.000000
7036,68.976667,124.404444,128.663333,57.830000,154.650000,165.865000,2016-10-24 17:20:00,17,1010.728655,1015.728655,354.674464,3.364912,20.164912,86.155945,0.0,0,1,17.333333
7037,53.837500,95.067500,123.625000,118.385556,160.040000,111.530000,2016-10-24 17:40:00,17,1010.722222,1015.722222,354.740741,3.366667,20.166667,86.148148,0.0,0,1,17.666667
7038,65.135000,109.605000,146.240000,104.990000,271.200000,110.325000,2016-10-24 18:00:00,18,1010.715789,1015.715789,354.807018,3.368421,20.168421,86.140351,0.0,0,1,18.000000
7039,61.346000,109.726667,136.015000,129.710000,260.345000,109.120000,2016-10-24 18:20:00,18,1010.709357,1015.709357,354.873294,3.370175,20.170175,86.132554,0.0,0,1,18.333333
7040,62.846250,165.638571,125.790000,46.317500,233.342500,120.622500,2016-10-24 18:40:00,18,1010.702924,1015.702924,354.939571,3.371930,20.171930,86.124756,0.0,0,1,18.666667
7041,63.601429,87.740000,106.190000,112.205000,206.340000,132.125000,2016-10-24 19:00:00,19,1010.696491,1015.696491,355.005848,3.373684,20.173684,86.116959,0.0,0,1,19.000000
7042,61.108571,129.976667,66.530000,118.240833,215.990000,143.627500,2016-10-24 19:20:00,19,1010.690058,1015.690058,355.072125,3.375439,20.175439,86.109162,0.0,0,1,19.333333
7043,57.263750,97.120000,95.630000,124.276667,182.305000,155.130000,2016-10-24 19:40:00,19,1010.683626,1015.683626,355.138402,3.377193,20.177193,86.101365,0.0,0,1,19.666667
7044,72.770000,104.550000,124.730000,101.357500,148.620000,211.398000,2016-10-24 20:00:00,20,1010.677193,1015.677193,355.204678,3.378947,20.178947,86.093567,0.0,0,1,20.000000
7045,48.822000,97.716000,78.360000,83.060000,137.581667,103.080000,2016-10-24 20:20:00,20,1010.670760,1015.670760,355.270955,3.380702,20.180702,86.085770,0.0,0,1,20.333333
7046,73.685000,88.840000,90.275000,111.510000,126.543333,101.660000,2016-10-24 20:40:00,20,1010.664327,1015.664327,355.337232,3.382456,20.182456,86.077973,0.0,0,1,20.666667
7047,65.890000,115.222000,102.190000,94.214000,115.505000,100.240000,2016-10-24 21:00:00,21,1010.657895,1015.657895,355.403509,3.384211,20.184211,86.070175,0.0,0,1,21.000000
7048,58.111667,80.610000,110.828333,76.918000,133.450000,98.820000,2016-10-24 21:20:00,21,1010.651462,1015.651462,355.469786,3.385965,20.185965,86.062378,0.0,0,1,21.333333
7049,57.962500,189.053333,119.466667,59.622000,140.285000,98.820000,2016-10-24 21:40:00,21,1010.645029,1015.645029,355.536062,3.387719,20.187719,86.054581,0.0,0,1,21.666667
7050,62.868571,88.450000,122.075000,42.326000,147.120000,98.820000,2016-10-24 22:00:00,22,1010.638596,1015.638596,355.602339,3.389474,20.189474,86.046784,0.0,0,1,22.000000
7051,73.112500,98.380000,86.100000,25.030000,153.955000,98.820000,2016-10-24 22:20:00,22,1010.632164,1015.632164,355.668616,3.391228,20.191228,86.038986,0.0,0,1,22.333333
7052,56.575000,151.580000,90.390000,93.250000,236.090000,98.820000,2016-10-24 22:40:00,22,1010.625731,1015.625731,355.734893,3.392982,20.192982,86.031189,0.0,0,1,22.666667
7053,51.330000,110.625000,80.935000,78.595000,236.090000,98.820000,2016-10-24 23:00:00,23,1010.619298,1015.619298,355.801170,3.394737,20.194737,86.023392,0.0,0,1,23.000000
7054,48.940000,69.670000,71.480000,63.940000,236.090000,98.820000,2016-10-24 23:20:00,23,1010.612865,1015.612865,355.867446,3.396491,20.196491,86.015595,0.0,0,1,23.333333
7055,54.310000,103.790000,117.900000,100.255000,236.090000,98.820000,2016-10-24 23:40:00,23,1010.606433,1015.606433,355.933723,3.398246,20.198246,86.007797,0.0,0,1,23.666667
7056,54.310000,103.790000,117.900000,100.255000,236.090000,98.820000,2016-10-25 00:00:00,0,1010.600000,1015.600000,356.000000,3.400000,20.200000,86.000000,0.0,1,0,0.000000

In [4]:
''' Cut some rows (proprecessing)'''
df_merged_volume = df_merged_volume[4:-1]  # Cut of NaN rows at the beginning, and the last row
df_merged_volume = df_merged_volume.reset_index(drop=True)  # reindexing
df_merged_volume

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
0,56.870000,94.570000,176.700000,107.487500,214.870000,119.210588,2016-07-19 01:20:00,1,1000.722222,1005.577778,215.888889,3.522222,29.366667,73.888889,0.0,1,0,1.333333
1,77.740000,88.916667,167.517778,93.720000,160.635000,122.045882,2016-07-19 01:40:00,1,1000.677778,1005.522222,215.111111,3.577778,29.833333,72.111111,0.0,1,0,1.666667
2,60.190000,83.263333,158.335556,67.810000,163.597778,124.881176,2016-07-19 02:00:00,2,1000.633333,1005.466667,214.333333,3.633333,30.300000,70.333333,0.0,1,0,2.000000
3,42.640000,77.610000,149.153333,117.677500,166.560556,127.716471,2016-07-19 02:20:00,2,1000.588889,1005.411111,213.555556,3.688889,30.766667,68.555556,0.0,1,0,2.333333
4,40.173333,85.350000,139.971111,167.545000,169.523333,130.551765,2016-07-19 02:40:00,2,1000.544444,1005.355556,212.777778,3.744444,31.233333,66.777778,0.0,1,0,2.666667
5,41.046667,93.090000,130.788889,144.526667,172.486111,133.387059,2016-07-19 03:00:00,3,1000.500000,1005.300000,212.000000,3.800000,31.700000,65.000000,0.0,1,0,3.000000
6,41.920000,92.794000,121.606667,121.508333,175.448889,136.222353,2016-07-19 03:20:00,3,1000.411111,1005.211111,215.000000,3.588889,31.711111,64.888889,0.0,1,0,3.333333
7,39.430000,92.498000,112.424444,98.490000,178.411667,139.057647,2016-07-19 03:40:00,3,1000.322222,1005.122222,218.000000,3.377778,31.722222,64.777778,0.0,1,0,3.666667
8,48.130000,92.202000,103.242222,96.670000,181.374444,141.892941,2016-07-19 04:00:00,4,1000.233333,1005.033333,221.000000,3.166667,31.733333,64.666667,0.0,1,0,4.000000
9,62.106667,91.906000,94.060000,53.150000,184.337222,144.728235,2016-07-19 04:20:00,4,1000.144444,1004.944444,224.000000,2.955556,31.744444,64.555556,0.0,1,0,4.333333
10,46.115000,91.610000,85.033333,55.245000,187.300000,147.563529,2016-07-19 04:40:00,4,1000.055556,1004.855556,227.000000,2.744444,31.755556,64.444444,0.0,1,0,4.666667
11,49.556000,129.985000,76.006667,209.660000,180.570000,150.398824,2016-07-19 05:00:00,5,999.966667,1004.766667,230.000000,2.533333,31.766667,64.333333,0.0,1,0,5.000000
12,54.840000,168.360000,66.980000,188.420000,173.840000,153.234118,2016-07-19 05:20:00,5,999.877778,1004.677778,233.000000,2.322222,31.777778,64.222222,0.0,1,0,5.333333
13,58.084286,146.510000,87.830000,167.180000,167.110000,156.069412,2016-07-19 05:40:00,5,999.788889,1004.588889,236.000000,2.111111,31.788889,64.111111,0.0,1,0,5.666667
14,46.356000,124.660000,170.090000,145.940000,160.380000,158.904706,2016-07-19 06:00:00,6,999.700000,1004.500000,239.000000,1.900000,31.800000,64.000000,0.0,1,0,6.000000
15,48.588000,89.846000,135.196667,127.350000,147.470000,161.740000,2016-07-19 06:20:00,6,999.588889,1004.388889,236.666667,1.911111,31.766667,64.555556,0.0,1,0,6.333333
16,66.642500,180.016000,100.303333,97.200000,134.560000,223.810000,2016-07-19 06:40:00,6,999.477778,1004.277778,234.333333,1.922222,31.733333,65.111111,0.0,1,0,6.666667
17,64.681000,101.395000,65.410000,118.428000,149.743333,135.920000,2016-07-19 07:00:00,7,999.366667,1004.166667,232.000000,1.933333,31.700000,65.666667,0.0,1,0,7.000000
18,85.676000,124.288000,81.245000,82.630000,164.926667,236.120000,2016-07-19 07:20:00,7,999.255556,1004.055556,229.666667,1.944444,31.666667,66.222222,0.0,1,0,7.333333
19,58.968889,155.495000,97.080000,110.500000,180.110000,178.425000,2016-07-19 07:40:00,7,999.144444,1003.944444,227.333333,1.955556,31.633333,66.777778,0.0,1,0,7.666667
20,81.602857,137.375000,112.915000,125.760000,151.386667,120.730000,2016-07-19 08:00:00,8,999.033333,1003.833333,225.000000,1.966667,31.600000,67.333333,0.0,1,0,8.000000
21,80.207857,165.482857,128.750000,141.334000,129.100000,143.370000,2016-07-19 08:20:00,8,998.922222,1003.722222,222.666667,1.977778,31.566667,67.888889,0.0,1,0,8.333333
22,63.448462,136.680000,71.893333,176.077143,164.983333,142.452500,2016-07-19 08:40:00,8,998.811111,1003.611111,220.333333,1.988889,31.533333,68.444444,0.0,1,0,8.666667
23,78.051176,192.680000,177.106667,165.290000,200.866667,141.535000,2016-07-19 09:00:00,9,998.700000,1003.500000,218.000000,2.000000,31.500000,69.000000,0.0,1,0,9.000000
24,69.038333,159.780000,104.330000,127.382500,164.520000,140.617500,2016-07-19 09:20:00,9,998.866667,1003.666667,217.666667,1.855556,31.333333,69.888889,0.0,1,0,9.333333
25,69.657143,129.275000,118.503333,117.827500,182.718333,139.700000,2016-07-19 09:40:00,9,999.033333,1003.833333,217.333333,1.711111,31.166667,70.777778,0.0,1,0,9.666667
26,78.311538,99.037500,132.676667,98.921667,200.916667,139.700000,2016-07-19 10:00:00,10,999.200000,1004.000000,217.000000,1.566667,31.000000,71.666667,0.0,1,0,10.000000
27,59.411818,129.300000,170.595000,112.998333,203.876000,114.250000,2016-07-19 10:20:00,10,999.366667,1004.166667,216.666667,1.422222,30.833333,72.555556,0.0,1,0,10.333333
28,75.488889,121.102857,79.570000,98.150000,301.280000,130.085714,2016-07-19 10:40:00,10,999.533333,1004.333333,216.333333,1.277778,30.666667,73.444444,0.0,1,0,10.666667
29,72.435000,104.786000,54.460000,95.983333,42.950000,145.921429,2016-07-19 11:00:00,11,999.700000,1004.500000,216.000000,1.133333,30.500000,74.333333,0.0,1,0,11.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7022,60.042727,93.555455,108.363333,104.692857,232.216667,198.340000,2016-10-24 14:00:00,14,1010.792982,1015.792982,354.011696,3.347368,20.147368,86.233918,0.0,0,1,14.000000
7023,49.277500,93.632500,121.066667,95.150000,201.725333,158.030000,2016-10-24 14:20:00,14,1010.786550,1015.786550,354.077973,3.349123,20.149123,86.226121,0.0,0,1,14.333333
7024,69.829474,96.445714,133.770000,74.277500,171.234000,125.450000,2016-10-24 14:40:00,14,1010.780117,1015.780117,354.144250,3.350877,20.150877,86.218324,0.0,0,1,14.666667
7025,95.172222,98.460000,123.783750,127.515000,168.852500,183.315000,2016-10-24 15:00:00,15,1010.773684,1015.773684,354.210526,3.352632,20.152632,86.210526,0.0,0,1,15.000000
7026,51.873636,106.870833,104.528000,76.680000,202.636667,144.675000,2016-10-24 15:20:00,15,1010.767251,1015.767251,354.276803,3.354386,20.154386,86.202729,0.0,0,1,15.333333
7027,44.688333,94.068000,102.053333,98.000000,175.865000,203.965000,2016-10-24 15:40:00,15,1010.760819,1015.760819,354.343080,3.356140,20.156140,86.194932,0.0,0,1,15.666667
7028,87.304667,111.742500,140.980000,65.323333,181.693333,159.366667,2016-10-24 16:00:00,16,1010.754386,1015.754386,354.409357,3.357895,20.157895,86.187135,0.0,0,1,16.000000
7029,67.715000,107.980000,111.556000,82.300000,188.636667,159.588333,2016-10-24 16:20:00,16,1010.747953,1015.747953,354.475634,3.359649,20.159649,86.179337,0.0,0,1,16.333333
7030,58.797778,147.760000,121.080000,109.508750,159.583333,159.810000,2016-10-24 16:40:00,16,1010.741520,1015.741520,354.541910,3.361404,20.161404,86.171540,0.0,0,1,16.666667
7031,85.030000,121.974167,114.141667,110.457778,190.150000,161.790000,2016-10-24 17:00:00,17,1010.735088,1015.735088,354.608187,3.363158,20.163158,86.163743,0.0,0,1,17.000000
7032,68.976667,124.404444,128.663333,57.830000,154.650000,165.865000,2016-10-24 17:20:00,17,1010.728655,1015.728655,354.674464,3.364912,20.164912,86.155945,0.0,0,1,17.333333
7033,53.837500,95.067500,123.625000,118.385556,160.040000,111.530000,2016-10-24 17:40:00,17,1010.722222,1015.722222,354.740741,3.366667,20.166667,86.148148,0.0,0,1,17.666667
7034,65.135000,109.605000,146.240000,104.990000,271.200000,110.325000,2016-10-24 18:00:00,18,1010.715789,1015.715789,354.807018,3.368421,20.168421,86.140351,0.0,0,1,18.000000
7035,61.346000,109.726667,136.015000,129.710000,260.345000,109.120000,2016-10-24 18:20:00,18,1010.709357,1015.709357,354.873294,3.370175,20.170175,86.132554,0.0,0,1,18.333333
7036,62.846250,165.638571,125.790000,46.317500,233.342500,120.622500,2016-10-24 18:40:00,18,1010.702924,1015.702924,354.939571,3.371930,20.171930,86.124756,0.0,0,1,18.666667
7037,63.601429,87.740000,106.190000,112.205000,206.340000,132.125000,2016-10-24 19:00:00,19,1010.696491,1015.696491,355.005848,3.373684,20.173684,86.116959,0.0,0,1,19.000000
7038,61.108571,129.976667,66.530000,118.240833,215.990000,143.627500,2016-10-24 19:20:00,19,1010.690058,1015.690058,355.072125,3.375439,20.175439,86.109162,0.0,0,1,19.333333
7039,57.263750,97.120000,95.630000,124.276667,182.305000,155.130000,2016-10-24 19:40:00,19,1010.683626,1015.683626,355.138402,3.377193,20.177193,86.101365,0.0,0,1,19.666667
7040,72.770000,104.550000,124.730000,101.357500,148.620000,211.398000,2016-10-24 20:00:00,20,1010.677193,1015.677193,355.204678,3.378947,20.178947,86.093567,0.0,0,1,20.000000
7041,48.822000,97.716000,78.360000,83.060000,137.581667,103.080000,2016-10-24 20:20:00,20,1010.670760,1015.670760,355.270955,3.380702,20.180702,86.085770,0.0,0,1,20.333333
7042,73.685000,88.840000,90.275000,111.510000,126.543333,101.660000,2016-10-24 20:40:00,20,1010.664327,1015.664327,355.337232,3.382456,20.182456,86.077973,0.0,0,1,20.666667
7043,65.890000,115.222000,102.190000,94.214000,115.505000,100.240000,2016-10-24 21:00:00,21,1010.657895,1015.657895,355.403509,3.384211,20.184211,86.070175,0.0,0,1,21.000000
7044,58.111667,80.610000,110.828333,76.918000,133.450000,98.820000,2016-10-24 21:20:00,21,1010.651462,1015.651462,355.469786,3.385965,20.185965,86.062378,0.0,0,1,21.333333
7045,57.962500,189.053333,119.466667,59.622000,140.285000,98.820000,2016-10-24 21:40:00,21,1010.645029,1015.645029,355.536062,3.387719,20.187719,86.054581,0.0,0,1,21.666667
7046,62.868571,88.450000,122.075000,42.326000,147.120000,98.820000,2016-10-24 22:00:00,22,1010.638596,1015.638596,355.602339,3.389474,20.189474,86.046784,0.0,0,1,22.000000
7047,73.112500,98.380000,86.100000,25.030000,153.955000,98.820000,2016-10-24 22:20:00,22,1010.632164,1015.632164,355.668616,3.391228,20.191228,86.038986,0.0,0,1,22.333333
7048,56.575000,151.580000,90.390000,93.250000,236.090000,98.820000,2016-10-24 22:40:00,22,1010.625731,1015.625731,355.734893,3.392982,20.192982,86.031189,0.0,0,1,22.666667
7049,51.330000,110.625000,80.935000,78.595000,236.090000,98.820000,2016-10-24 23:00:00,23,1010.619298,1015.619298,355.801170,3.394737,20.194737,86.023392,0.0,0,1,23.000000
7050,48.940000,69.670000,71.480000,63.940000,236.090000,98.820000,2016-10-24 23:20:00,23,1010.612865,1015.612865,355.867446,3.396491,20.196491,86.015595,0.0,0,1,23.333333
7051,54.310000,103.790000,117.900000,100.255000,236.090000,98.820000,2016-10-24 23:40:00,23,1010.606433,1015.606433,355.933723,3.398246,20.198246,86.007797,0.0,0,1,23.666667

In [5]:
# Check all the columns

for idx, i in enumerate(df_merged_volume.columns):
    print(idx, i)

0 ('A', 2)
1 ('A', 3)
2 ('B', 1)
3 ('B', 3)
4 ('C', 1)
5 ('C', 3)
6 date
7 hour
8 pressure
9 sea_pressure
10 wind_direction
11 wind_speed
12 temperature
13 rel_humidity
14 precipitation
15 dayofweek
16 is_holiday
17 timeofday

In [6]:
''' Make the dataset stationary '''

station_cols = 6  # select the first 6 columns for stationary

df_merged_volume_copy = df_merged_volume.copy()

for i in range(1, len(df_merged_volume_copy)):
    df_merged_volume_copy.loc[i, df_merged_volume_copy.columns[0:station_cols]] = df_merged_volume.loc[i, df_merged_volume.columns[0:station_cols]] - df_merged_volume.loc[i-1, df_merged_volume.columns[0:station_cols]]

In [7]:
# Check Stationary dataframe

df_merged_volume_copy

,"('A', 2)","('A', 3)","('B', 1)","('B', 3)","('C', 1)","('C', 3)",date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,dayofweek,is_holiday,timeofday
0,56.870000,94.570000,176.700000,107.487500,214.870000,119.210588,2016-07-19 01:20:00,1,1000.722222,1005.577778,215.888889,3.522222,29.366667,73.888889,0.0,1,0,1.333333
1,20.870000,-5.653333,-9.182222,-13.767500,-54.235000,2.835294,2016-07-19 01:40:00,1,1000.677778,1005.522222,215.111111,3.577778,29.833333,72.111111,0.0,1,0,1.666667
2,-17.550000,-5.653333,-9.182222,-25.910000,2.962778,2.835294,2016-07-19 02:00:00,2,1000.633333,1005.466667,214.333333,3.633333,30.300000,70.333333,0.0,1,0,2.000000
3,-17.550000,-5.653333,-9.182222,49.867500,2.962778,2.835294,2016-07-19 02:20:00,2,1000.588889,1005.411111,213.555556,3.688889,30.766667,68.555556,0.0,1,0,2.333333
4,-2.466667,7.740000,-9.182222,49.867500,2.962778,2.835294,2016-07-19 02:40:00,2,1000.544444,1005.355556,212.777778,3.744444,31.233333,66.777778,0.0,1,0,2.666667
5,0.873333,7.740000,-9.182222,-23.018333,2.962778,2.835294,2016-07-19 03:00:00,3,1000.500000,1005.300000,212.000000,3.800000,31.700000,65.000000,0.0,1,0,3.000000
6,0.873333,-0.296000,-9.182222,-23.018333,2.962778,2.835294,2016-07-19 03:20:00,3,1000.411111,1005.211111,215.000000,3.588889,31.711111,64.888889,0.0,1,0,3.333333
7,-2.490000,-0.296000,-9.182222,-23.018333,2.962778,2.835294,2016-07-19 03:40:00,3,1000.322222,1005.122222,218.000000,3.377778,31.722222,64.777778,0.0,1,0,3.666667
8,8.700000,-0.296000,-9.182222,-1.820000,2.962778,2.835294,2016-07-19 04:00:00,4,1000.233333,1005.033333,221.000000,3.166667,31.733333,64.666667,0.0,1,0,4.000000
9,13.976667,-0.296000,-9.182222,-43.520000,2.962778,2.835294,2016-07-19 04:20:00,4,1000.144444,1004.944444,224.000000,2.955556,31.744444,64.555556,0.0,1,0,4.333333
10,-15.991667,-0.296000,-9.026667,2.095000,2.962778,2.835294,2016-07-19 04:40:00,4,1000.055556,1004.855556,227.000000,2.744444,31.755556,64.444444,0.0,1,0,4.666667
11,3.441000,38.375000,-9.026667,154.415000,-6.730000,2.835294,2016-07-19 05:00:00,5,999.966667,1004.766667,230.000000,2.533333,31.766667,64.333333,0.0,1,0,5.000000
12,5.284000,38.375000,-9.026667,-21.240000,-6.730000,2.835294,2016-07-19 05:20:00,5,999.877778,1004.677778,233.000000,2.322222,31.777778,64.222222,0.0,1,0,5.333333
13,3.244286,-21.850000,20.850000,-21.240000,-6.730000,2.835294,2016-07-19 05:40:00,5,999.788889,1004.588889,236.000000,2.111111,31.788889,64.111111,0.0,1,0,5.666667
14,-11.728286,-21.850000,82.260000,-21.240000,-6.730000,2.835294,2016-07-19 06:00:00,6,999.700000,1004.500000,239.000000,1.900000,31.800000,64.000000,0.0,1,0,6.000000
15,2.232000,-34.814000,-34.893333,-18.590000,-12.910000,2.835294,2016-07-19 06:20:00,6,999.588889,1004.388889,236.666667,1.911111,31.766667,64.555556,0.0,1,0,6.333333
16,18.054500,90.170000,-34.893333,-30.150000,-12.910000,62.070000,2016-07-19 06:40:00,6,999.477778,1004.277778,234.333333,1.922222,31.733333,65.111111,0.0,1,0,6.666667
17,-1.961500,-78.621000,-34.893333,21.228000,15.183333,-87.890000,2016-07-19 07:00:00,7,999.366667,1004.166667,232.000000,1.933333,31.700000,65.666667,0.0,1,0,7.000000
18,20.995000,22.893000,15.835000,-35.798000,15.183333,100.200000,2016-07-19 07:20:00,7,999.255556,1004.055556,229.666667,1.944444,31.666667,66.222222,0.0,1,0,7.333333
19,-26.707111,31.207000,15.835000,27.870000,15.183333,-57.695000,2016-07-19 07:40:00,7,999.144444,1003.944444,227.333333,1.955556,31.633333,66.777778,0.0,1,0,7.666667
20,22.633968,-18.120000,15.835000,15.260000,-28.723333,-57.695000,2016-07-19 08:00:00,8,999.033333,1003.833333,225.000000,1.966667,31.600000,67.333333,0.0,1,0,8.000000
21,-1.395000,28.107857,15.835000,15.574000,-22.286667,22.640000,2016-07-19 08:20:00,8,998.922222,1003.722222,222.666667,1.977778,31.566667,67.888889,0.0,1,0,8.333333
22,-16.759396,-28.802857,-56.856667,34.743143,35.883333,-0.917500,2016-07-19 08:40:00,8,998.811111,1003.611111,220.333333,1.988889,31.533333,68.444444,0.0,1,0,8.666667
23,14.602715,56.000000,105.213333,-10.787143,35.883333,-0.917500,2016-07-19 09:00:00,9,998.700000,1003.500000,218.000000,2.000000,31.500000,69.000000,0.0,1,0,9.000000
24,-9.012843,-32.900000,-72.776667,-37.907500,-36.346667,-0.917500,2016-07-19 09:20:00,9,998.866667,1003.666667,217.666667,1.855556,31.333333,69.888889,0.0,1,0,9.333333
25,0.618810,-30.505000,14.173333,-9.555000,18.198333,-0.917500,2016-07-19 09:40:00,9,999.033333,1003.833333,217.333333,1.711111,31.166667,70.777778,0.0,1,0,9.666667
26,8.654396,-30.237500,14.173333,-18.905833,18.198333,0.000000,2016-07-19 10:00:00,10,999.200000,1004.000000,217.000000,1.566667,31.000000,71.666667,0.0,1,0,10.000000
27,-18.899720,30.262500,37.918333,14.076667,2.959333,-25.450000,2016-07-19 10:20:00,10,999.366667,1004.166667,216.666667,1.422222,30.833333,72.555556,0.0,1,0,10.333333
28,16.077071,-8.197143,-91.025000,-14.848333,97.404000,15.835714,2016-07-19 10:40:00,10,999.533333,1004.333333,216.333333,1.277778,30.666667,73.444444,0.0,1,0,10.666667
29,-3.053889,-16.316857,-25.110000,-2.166667,-258.330000,15.835714,2016-07-19 11:00:00,11,999.700000,1004.500000,216.000000,1.133333,30.500000,74.333333,0.0,1,0,11.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7022,-6.731558,-7.184545,-9.960000,-24.264286,15.405000,10.315000,2016-10-24 14:00:00,14,1010.792982,1015.792982,354.011696,3.347368,20.147368,86.233918,0.0,0,1,14.000000
7023,-10.765227,0.077045,12.703333,-9.542857,-30.491333,-40.310000,2016-10-24 14:20:00,14,1010.786550,1015.786550,354.077973,3.349123,20.149123,86.226121,0.0,0,1,14.333333
7024,20.551974,2.813214,12.703333,-20.872500,-30.491333,-32.580000,2016-10-24 14:40:00,14,1010.780117,1015.780117,354.144250,3.350877,20.150877,86.218324,0.0,0,1,14.666667
7025,25.342749,2.014286,-9.986250,53.237500,-2.381500,57.865000,2016-10-24 15:00:00,15,1010.773684,1015.773684,354.210526,3.352632,20.152632,86.210526,0.0,0,1,15.000000
7026,-43.298586,8.410833,-19.255750,-50.835000,33.784167,-38.640000,2016-10-24 15:20:00,15,1010.767251,1015.767251,354.276803,3.354386,20.154386,86.202729,0.0,0,1,15.333333
7027,-7.185303,-12.802833,-2.474667,21.320000,-26.771667,59.290000,2016-10-24 15:40:00,15,1010.760819,1015.760819,354.343080,3.356140,20.156140,86.194932,0.0,0,1,15.666667
7028,42.616333,17.674500,38.926667,-32.676667,5.828333,-44.598333,2016-10-24 16:00:00,16,1010.754386,1015.754386,354.409357,3.357895,20.157895,86.187135,0.0,0,1,16.000000
7029,-19.589667,-3.762500,-29.424000,16.976667,6.943333,0.221667,2016-10-24 16:20:00,16,1010.747953,1015.747953,354.475634,3.359649,20.159649,86.179337,0.0,0,1,16.333333
7030,-8.917222,39.780000,9.524000,27.208750,-29.053333,0.221667,2016-10-24 16:40:00,16,1010.741520,1015.741520,354.541910,3.361404,20.161404,86.171540,0.0,0,1,16.666667
7031,26.232222,-25.785833,-6.938333,0.949028,30.566667,1.980000,2016-10-24 17:00:00,17,1010.735088,1015.735088,354.608187,3.363158,20.163158,86.163743,0.0,0,1,17.000000
7032,-16.053333,2.430278,14.521667,-52.627778,-35.500000,4.075000,2016-10-24 17:20:00,17,1010.728655,1015.728655,354.674464,3.364912,20.164912,86.155945,0.0,0,1,17.333333
7033,-15.139167,-29.336944,-5.038333,60.555556,5.390000,-54.335000,2016-10-24 17:40:00,17,1010.722222,1015.722222,354.740741,3.366667,20.166667,86.148148,0.0,0,1,17.666667
7034,11.297500,14.537500,22.615000,-13.395556,111.160000,-1.205000,2016-10-24 18:00:00,18,1010.715789,1015.715789,354.807018,3.368421,20.168421,86.140351,0.0,0,1,18.000000
7035,-3.789000,0.121667,-10.225000,24.720000,-10.855000,-1.205000,2016-10-24 18:20:00,18,1010.709357,1015.709357,354.873294,3.370175,20.170175,86.132554,0.0,0,1,18.333333
7036,1.500250,55.911905,-10.225000,-83.392500,-27.002500,11.502500,2016-10-24 18:40:00,18,1010.702924,1015.702924,354.939571,3.371930,20.171930,86.124756,0.0,0,1,18.666667
7037,0.755179,-77.898571,-19.600000,65.887500,-27.002500,11.502500,2016-10-24 19:00:00,19,1010.696491,1015.696491,355.005848,3.373684,20.173684,86.116959,0.0,0,1,19.000000
7038,-2.492857,42.236667,-39.660000,6.035833,9.650000,11.502500,2016-10-24 19:20:00,19,1010.690058,1015.690058,355.072125,3.375439,20.175439,86.109162,0.0,0,1,19.333333
7039,-3.844821,-32.856667,29.100000,6.035833,-33.685000,11.502500,2016-10-24 19:40:00,19,1010.683626,1015.683626,355.138402,3.377193,20.177193,86.101365,0.0,0,1,19.666667
7040,15.506250,7.430000,29.100000,-22.919167,-33.685000,56.268000,2016-10-24 20:00:00,20,1010.677193,1015.677193,355.204678,3.378947,20.178947,86.093567,0.0,0,1,20.000000
7041,-23.948000,-6.834000,-46.370000,-18.297500,-11.038333,-108.318000,2016-10-24 20:20:00,20,1010.670760,1015.670760,355.270955,3.380702,20.180702,86.085770,0.0,0,1,20.333333
7042,24.863000,-8.876000,11.915000,28.450000,-11.038333,-1.420000,2016-10-24 20:40:00,20,1010.664327,1015.664327,355.337232,3.382456,20.182456,86.077973,0.0,0,1,20.666667
7043,-7.795000,26.382000,11.915000,-17.296000,-11.038333,-1.420000,2016-10-24 21:00:00,21,1010.657895,1015.657895,355.403509,3.384211,20.184211,86.070175,0.0,0,1,21.000000
7044,-7.778333,-34.612000,8.638333,-17.296000,17.945000,-1.420000,2016-10-24 21:20:00,21,1010.651462,1015.651462,355.469786,3.385965,20.185965,86.062378,0.0,0,1,21.333333
7045,-0.149167,108.443333,8.638333,-17.296000,6.835000,0.000000,2016-10-24 21:40:00,21,1010.645029,1015.645029,355.536062,3.387719,20.187719,86.054581,0.0,0,1,21.666667
7046,4.906071,-100.603333,2.608333,-17.296000,6.835000,0.000000,2016-10-24 22:00:00,22,1010.638596,1015.638596,355.602339,3.389474,20.189474,86.046784,0.0,0,1,22.000000
7047,10.243929,9.930000,-35.975000,-17.296000,6.835000,0.000000,2016-10-24 22:20:00,22,1010.632164,1015.632164,355.668616,3.391228,20.191228,86.038986,0.0,0,1,22.333333
7048,-16.537500,53.200000,4.290000,68.220000,82.135000,0.000000,2016-10-24 22:40:00,22,1010.625731,1015.625731,355.734893,3.392982,20.192982,86.031189,0.0,0,1,22.666667
7049,-5.245000,-40.955000,-9.455000,-14.655000,0.000000,0.000000,2016-10-24 23:00:00,23,1010.619298,1015.619298,355.801170,3.394737,20.194737,86.023392,0.0,0,1,23.000000
7050,-2.390000,-40.955000,-9.455000,-14.655000,0.000000,0.000000,2016-10-24 23:20:00,23,1010.612865,1015.612865,355.867446,3.396491,20.196491,86.015595,0.0,0,1,23.333333
7051,5.370000,34.120000,46.420000,36.315000,0.000000,0.000000,2016-10-24 23:40:00,23,1010.606433,1015.606433,355.933723,3.398246,20.198246,86.007797,0.0,0,1,23.666667

In [8]:
## Hidden the selecting time
# select the time for training: 6:20-10:00 (5 + 6 timestamp) and 15:20-19:00 (5 + 6 timestamp)
# sel_rows = df_merged_volume_copy[ ((df_merged_volume_copy.timeofday>= 6.3) & (df_merged_volume_copy.timeofday<10)) |
#                             ((df_merged_volume_copy.timeofday>=15.3) & (df_merged_volume_copy.timeofday<19))]

## This time, training all time (24hrs) except the first non-stationary row
sel_rows = df_merged_volume_copy[1:]

In [9]:
# select using columns

using_cols = [
#                 "(1, 0, 'cargocar')",
#                 "(1, 0, 'etc')",
#                 "(1, 0, 'motorcycle')",
#                 "(1, 0, 'privatecar')",
#                 "(1, 0, 'tot')",
#                 "(1, 0, 'unknowncar')",
#                 "(1, 1, 'cargocar')",
#                 "(1, 1, 'etc')",
#                 "(1, 1, 'motorcycle')",
#                 "(1, 1, 'privatecar')",
#                 "(1, 1, 'tot')",
#                 "(1, 1, 'unknowncar')",
#                 "(2, 0, 'cargocar')",
#                 "(2, 0, 'etc')",
#                 "(2, 0, 'motorcycle')",
#                 "(2, 0, 'privatecar')",
#                 "(2, 0, 'tot')",
#                 "(2, 0, 'unknowncar')",
#                 "(3, 0, 'cargocar')",
#                 "(3, 0, 'etc')",
#                 "(3, 0, 'motorcycle')",
#                 "(3, 0, 'privatecar')",
#                 "(3, 0, 'tot')",
#                 "(3, 0, 'unknowncar')",
#                 "(3, 1, 'cargocar')",
#                 "(3, 1, 'etc')",
#                 "(3, 1, 'motorcycle')",
#                 "(3, 1, 'privatecar')",
#                 "(3, 1, 'tot')",
#                 "(3, 1, 'unknowncar')",
                "('A', 2)",
#                 "('A', 3)",
#                 "('B', 1)",
#                 "('B', 3)",
#                 "('C', 1)",
#                 "('C', 3)",
#                 'date',  # <== Notice this
                'hour',
                'pressure',
#                 'sea_pressure',
#                 'wind_direction',
#                 'wind_speed',
                'temperature',
#                 'rel_humidity',
                'precipitation',
                'dayofweek',
                'is_holiday',
                'timeofday'
              ]

sel_rows = sel_rows[using_cols]

In [48]:
# split to train and valid set
train_rows = sel_rows
valid_rows = sel_rows[-24*3*7:] # reserve 7 days for validation

# get numpy array from panda dataframe
train_arr = train_rows.values
valid_arr = valid_rows.values

# np.shape(train_arr)
# Out:
# (726, 17)

In [49]:
#scale feature array to range -1 to 1

scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = scaler.fit(train_arr)
train_scaled_arr = scaler.transform(train_arr)

valid_scaled_arr = scaler.transform(valid_arr)

In [50]:
# sample subsequence from the time series
train_seqs = []
len_seqs = len(train_scaled_arr) - 6 + 1  # 6 is window size
for i in range(len_seqs):
    train_seqs.append(train_scaled_arr[i: i+6])  # append 6 timestamps each time (5 timestamps for x, 1 timestamp for y)
train_seqs = np.stack(train_seqs)

valid_seqs = []
len_v_seqs = len(valid_scaled_arr) - 6 + 1  # 6 is window size
for i in range(len_v_seqs):
    valid_seqs.append(valid_scaled_arr[i: i+6])
valid_seqs = np.stack(valid_seqs)

In [51]:
# checking
train_seqs[:,:,:].shape

(7046, 6, 8)

In [52]:
#keras
#https://keras.io/getting-started/sequential-model-guide/#examples
input_dim = len(using_cols)  # The features
output_dim = 1  # 
timesteps = 5 # use 5 timesteps to predict the 6th

x_train, y_train = train_seqs[:, 0:-1], train_seqs[:, -1, 0:output_dim]  # 0:output_dim is for deciding the output features
x_valid , y_valid  =  valid_seqs[:, 0:-1],  valid_seqs[:, -1, 0:output_dim]  # 0:output_dim is for deciding the output features

In [53]:
y_train.shape

(7046, 1)

In [54]:
num_epochs = 200
loss_fuc = 'mean_squared_error'

# construct the callback
filepath="best_epoch_T.M._A-2_improved_kf.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

model = Sequential()
model.add(LSTM(128, input_shape=(timesteps, input_dim), return_sequences=True))
model.add(LSTM(128))
model.add(Dense(output_dim))
model.compile(loss=loss_fuc, optimizer='adam')

In [ ]:
## Start Training
model.summary()

# Cross Validation
n_folds = 5
kf = KFold(n_splits=n_folds)

for i , (train, valid) in enumerate(kf.split(x_train)):
    print('Fold: {}'.format(i))
    history_w_model = model.fit(x_train[train], y_train[train], callbacks=callbacks_list, epochs=num_epochs, batch_size=64, validation_data=(x_train[valid], y_train[valid]))

    plt.plot(history_w_model.history['loss'], label='loss')
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.plot(history_w_model.history['val_loss'], label='Val_loss')
    plt.show()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_5 (LSTM)                (None, 5, 128)            70144
_________________________________________________________________
lstm_6 (LSTM)                (None, 128)               131584
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129
=================================================================
Total params: 201,857
Trainable params: 201,857
Non-trainable params: 0
_________________________________________________________________
Fold: 0
Train on 5636 samples, validate on 1410 samples
Epoch 1/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0066Epoch 00000: val_loss improved from inf to 0.00326, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 7s - loss: 0.0066 - val_loss: 0.0033
Epoch 2/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0032Epoch 00001: val_loss improved from 0.00326 to 0.00320, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 5s - loss: 0.0032 - val_loss: 0.0032
Epoch 3/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0032Epoch 00002: val_loss improved from 0.00320 to 0.00311, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 5s - loss: 0.0032 - val_loss: 0.0031
Epoch 4/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0031Epoch 00003: val_loss improved from 0.00311 to 0.00306, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 5s - loss: 0.0031 - val_loss: 0.0031
Epoch 5/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0031Epoch 00004: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0031 - val_loss: 0.0032
Epoch 6/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0031Epoch 00005: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0031 - val_loss: 0.0031
Epoch 7/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0030Epoch 00006: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0030 - val_loss: 0.0034
Epoch 8/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0031Epoch 00007: val_loss improved from 0.00306 to 0.00305, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0031 - val_loss: 0.0030
Epoch 9/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0030Epoch 00008: val_loss improved from 0.00305 to 0.00301, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0030 - val_loss: 0.0030
Epoch 10/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0030Epoch 00009: val_loss improved from 0.00301 to 0.00301, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0030 - val_loss: 0.0030
Epoch 11/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0030Epoch 00010: val_loss improved from 0.00301 to 0.00299, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0030 - val_loss: 0.0030
Epoch 12/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0029Epoch 00011: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0029 - val_loss: 0.0031
Epoch 13/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0029Epoch 00012: val_loss improved from 0.00299 to 0.00294, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0029 - val_loss: 0.0029
Epoch 14/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0029Epoch 00013: val_loss improved from 0.00294 to 0.00286, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0029 - val_loss: 0.0029
Epoch 15/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0028Epoch 00014: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0028 - val_loss: 0.0030
Epoch 16/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0027Epoch 00015: val_loss improved from 0.00286 to 0.00274, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0027 - val_loss: 0.0027
Epoch 17/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0026Epoch 00016: val_loss improved from 0.00274 to 0.00257, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0026 - val_loss: 0.0026
Epoch 18/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0025Epoch 00017: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0025 - val_loss: 0.0026
Epoch 19/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0025Epoch 00018: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0025 - val_loss: 0.0026
Epoch 20/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0025Epoch 00019: val_loss improved from 0.00257 to 0.00239, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0025 - val_loss: 0.0024
Epoch 21/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0024Epoch 00020: val_loss improved from 0.00239 to 0.00238, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0024 - val_loss: 0.0024
Epoch 22/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0024Epoch 00021: val_loss improved from 0.00238 to 0.00228, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0024 - val_loss: 0.0023
Epoch 23/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0023Epoch 00022: val_loss did not improve
5636/5636 [==============================] - 5s - loss: 0.0023 - val_loss: 0.0023
Epoch 24/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0024Epoch 00023: val_loss did not improve
5636/5636 [==============================] - 6s - loss: 0.0024 - val_loss: 0.0023
Epoch 25/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0023Epoch 00024: val_loss improved from 0.00228 to 0.00227, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0023 - val_loss: 0.0023
Epoch 26/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0023Epoch 00025: val_loss did not improve
5636/5636 [==============================] - 5s - loss: 0.0023 - val_loss: 0.0023
Epoch 27/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0022Epoch 00026: val_loss improved from 0.00227 to 0.00219, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0022 - val_loss: 0.0022
Epoch 28/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0023Epoch 00027: val_loss improved from 0.00219 to 0.00219, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 6s - loss: 0.0023 - val_loss: 0.0022
Epoch 29/200
5632/5636 [============================>.] - ETA: 0s - loss: 0.0022Epoch 00028: val_loss improved from 0.00219 to 0.00218, saving model to best_epoch_T.M._A-2_improved_kf.hdf5
5636/5636 [==============================] - 5s - loss: 0.0022 - val_loss: 0.0022
Epoch 30/200
4864/5636 [========================>.....] - ETA: 0s - loss: 0.0023

In [36]:
# load weights into the model
model.load_weights("best_epoch_T.M._A-2.hdf5")
print("Loaded model from disk")

model.compile(loss='mean_squared_error', optimizer='adam')

Loaded model from disk

In [20]:
''' === Prediction ===
Procedure:
1. Load CSV
2. to_datetime
3. create timeofday column
4. select the time for training: 6:00-8:00 (6 timestamps) and 15:00-17:00 (6 timestamps)
5. change it to stationary
6. Use using_cols to select the features
7. change to np array
8. MinMaxScaler
9. make the sequences tensor as input
10. make a forloop for prediction

'''
# 1. Load CSV - Vol + Route + Weather (Only Weather is 24-hour data)
df_pred = pd.read_csv('../data/preprocessed_input_interpolate_20min_phase1and2_train.csv')

# 2. to_datetime
df_pred['date'] = pd.to_datetime(df_pred['date'])

# 3. create timeofday column
df_pred['timeofday'] = df_pred.date.apply( lambda d : d.hour+d.minute/60.)

In [21]:
# Select the checking days (No need to real final test)

import datetime

start_day = datetime.datetime(year=2016, month=10, day=18, hour=1, minute=0, second=0)
end_day = datetime.datetime(year=2016, month=10, day=24, hour=23, minute=0, second=0)

df_pred['date'] > start_day

df_pred_sel = df_pred[(df_pred['date'] > start_day) & (df_pred['date'] < end_day)]

In [22]:
# 4. select the time for training

df_pred_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 6) & (df_pred_sel.timeofday<8)) |
                            ((df_pred_sel.timeofday>=15) & (df_pred_sel.timeofday<17))]

df_feedin_weather_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 8) & (df_pred_sel.timeofday<10)) |
                            ((df_pred_sel.timeofday>=17) & (df_pred_sel.timeofday<19))]

In [47]:
# Checking
df_pred_sel_time.iloc[12]

(1, 0, 'cargocar')                        0
(1, 0, 'etc')                             1
(1, 0, 'motorcycle')                      0
(1, 0, 'privatecar')                      0
(1, 0, 'tot')                            12
(1, 0, 'unknowncar')                     12
(1, 1, 'cargocar')                       28
(1, 1, 'etc')                             6
(1, 1, 'motorcycle')                     20
(1, 1, 'privatecar')                      0
(1, 1, 'tot')                            48
(1, 1, 'unknowncar')                      0
(2, 0, 'cargocar')                        0
(2, 0, 'etc')                             6
(2, 0, 'motorcycle')                      0
(2, 0, 'privatecar')                      0
(2, 0, 'tot')                            26
(2, 0, 'unknowncar')                     26
(3, 0, 'cargocar')                        0
(3, 0, 'etc')                             3
(3, 0, 'motorcycle')                      0
(3, 0, 'privatecar')                      0
(3, 0, 'tot')                            24
(3, 0, 'unknowncar')                     24
(3, 1, 'cargocar')                       14
(3, 1, 'etc')                             2
(3, 1, 'motorcycle')                      6
(3, 1, 'privatecar')                      1
(3, 1, 'tot')                            21
(3, 1, 'unknowncar')                      0
('A', 2)                              40.01
('A', 3)                              89.51
('B', 1)                            111.035
('B', 3)                             102.83
('C', 1)                            160.492
('C', 3)                             126.74
date                    2016-10-19 06:00:00
hour                                      6
pressure                            1013.26
sea_pressure                        1018.26
wind_direction                      328.561
wind_speed                          2.67368
temperature                         19.4737
rel_humidity                        89.2281
precipitation                             0
dayofweek                                 2
is_holiday                                0
timeofday                                 6
Name: 2106, dtype: object

In [23]:
# 5. change it to stationary
df_pred_sel_time = df_pred_sel_time.reset_index(drop=True)

df_pred_sel_time_copy = df_pred_sel_time.copy()

for i in range(len(df_pred_sel_time_copy)//6):  # make the loop for 14 time slots (2 different time slot x 7days)
    for t in range(5):  #  Do the "difference" 5 times every loop
        start_idx = i*6 + t + 1  # Add 1 is for starting it from index 1 in every 6-space time slot
        df_pred_sel_time_copy.loc[start_idx, df_pred_sel_time_copy.columns[0:36]] = df_pred_sel_time.loc[start_idx, df_pred_sel_time.columns[0:36]] - df_pred_sel_time.loc[start_idx-1, df_pred_sel_time.columns[0:36]]

In [24]:
# 6. Use using_cols to select the features
sel_rows_pred = df_pred_sel_time_copy[ using_cols ]

sel_rows_feedin_weather = df_feedin_weather_sel_time[using_cols[output_dim:]]

In [25]:
sel_rows_pred

,"('A', 2)",hour,pressure,temperature,precipitation,dayofweek,is_holiday,timeofday
0,41.097143,6,1013.726316,19.347368,0.0,1,0,6.000000
1,2.584524,6,1013.719883,19.349123,0.0,1,0,6.333333
2,24.342619,6,1013.713450,19.350877,0.0,1,0,6.666667
3,-15.415952,7,1013.707018,19.352632,0.0,1,0,7.000000
4,3.557222,7,1013.700585,19.354386,0.0,1,0,7.333333
5,7.433016,7,1013.694152,19.356140,0.0,1,0,7.666667
6,99.960667,15,1013.552632,19.394737,0.0,1,0,15.000000
7,-11.600111,15,1013.546199,19.396491,0.0,1,0,15.333333
8,-13.474556,15,1013.539766,19.398246,0.0,1,0,15.666667
9,-11.583273,16,1013.533333,19.400000,0.0,1,0,16.000000
10,8.059273,16,1013.526901,19.401754,0.0,1,0,16.333333
11,27.898909,16,1013.520468,19.403509,0.0,1,0,16.666667
12,40.010000,6,1013.263158,19.473684,0.0,2,0,6.000000
13,16.997273,6,1013.256725,19.475439,0.0,2,0,6.333333
14,-19.595273,6,1013.250292,19.477193,0.0,2,0,6.666667
15,32.172000,7,1013.243860,19.478947,0.0,2,0,7.000000
16,30.530000,7,1013.237427,19.480702,0.0,2,0,7.333333
17,-41.821857,7,1013.230994,19.482456,0.0,2,0,7.666667
18,64.462857,15,1013.089474,19.521053,0.0,2,0,15.000000
19,-2.155079,15,1013.083041,19.522807,0.0,2,0,15.333333
20,-4.977778,15,1013.076608,19.524561,0.0,2,0,15.666667
21,10.254000,16,1013.070175,19.526316,0.0,2,0,16.000000
22,-12.394000,16,1013.063743,19.528070,0.0,2,0,16.333333
23,17.286364,16,1013.057310,19.529825,0.0,2,0,16.666667
24,63.584000,6,1012.800000,19.600000,0.0,3,0,6.000000
25,-13.790667,6,1012.793567,19.601754,0.0,3,0,6.333333
26,11.091667,6,1012.787135,19.603509,0.0,3,0,6.666667
27,13.188750,7,1012.780702,19.605263,0.0,3,0,7.000000
28,-11.085179,7,1012.774269,19.607018,0.0,3,0,7.333333
29,12.805000,7,1012.767836,19.608772,0.0,3,0,7.666667
...,...,...,...,...,...,...,...,...
54,63.869000,15,1011.700000,19.900000,0.0,5,0,15.000000
55,4.286000,15,1011.693567,19.901754,0.0,5,0,15.333333
56,-9.359286,15,1011.687135,19.903509,0.0,5,0,15.666667
57,10.182857,16,1011.680702,19.905263,0.0,5,0,16.000000
58,13.088701,16,1011.674269,19.907018,0.0,5,0,16.333333
59,-16.080350,16,1011.667836,19.908772,0.0,5,0,16.666667
60,71.920000,6,1011.410526,19.978947,0.0,6,1,6.000000
61,-2.940000,6,1011.404094,19.980702,0.0,6,1,6.333333
62,8.085714,6,1011.397661,19.982456,0.0,6,1,6.666667
63,-33.685714,7,1011.391228,19.984211,0.0,6,1,7.000000
64,6.156667,7,1011.384795,19.985965,0.0,6,1,7.333333
65,16.593333,7,1011.378363,19.987719,0.0,6,1,7.666667
66,94.766364,15,1011.236842,20.026316,0.0,6,1,15.000000
67,-15.377792,15,1011.230409,20.028070,0.0,6,1,15.333333
68,13.116429,15,1011.223977,20.029825,0.0,6,1,15.666667
69,-21.194231,16,1011.217544,20.031579,0.0,6,1,16.000000
70,3.882564,16,1011.211111,20.033333,0.0,6,1,16.333333
71,-3.626905,16,1011.204678,20.035088,0.0,6,1,16.666667
72,41.188333,6,1010.947368,20.105263,0.0,0,1,6.000000
73,8.927381,6,1010.940936,20.107018,0.0,0,1,6.333333
74,-12.947714,6,1010.934503,20.108772,0.0,0,1,6.666667
75,38.515750,7,1010.928070,20.110526,0.0,0,1,7.000000
76,-21.650893,7,1010.921637,20.112281,0.0,0,1,7.333333
77,24.245143,7,1010.915205,20.114035,0.0,0,1,7.666667
78,95.172222,15,1010.773684,20.152632,0.0,0,1,15.000000
79,-43.298586,15,1010.767251,20.154386,0.0,0,1,15.333333
80,-7.185303,15,1010.760819,20.156140,0.0,0,1,15.666667
81,42.616333,16,1010.754386,20.157895,0.0,0,1,16.000000
82,-19.589667,16,1010.747953,20.159649,0.0,0,1,16.333333
83,-8.917222,16,1010.741520,20.161404,0.0,0,1,16.666667

In [26]:
# 7. change to np array
pred_arr = sel_rows_pred.values

feedin_weather_arr = sel_rows_feedin_weather.values

# 8. MinMaxScaler
pred_arr_scaled = scaler.transform(pred_arr)

# add some dummy cells in front of the weather_array for transform
temp_arr = np.zeros((84,output_dim))
feedin_weather_arr = np.concatenate([temp_arr, feedin_weather_arr], axis=1)

feedin_weather_arr_scaled = scaler.transform(feedin_weather_arr)

# Now pred_arr_scaled is (84 x features)

In [27]:
# 9. make the sequences tensor as input
# Put into the model to get the prediction

ans_arr = []  # For holding the output answer
    
for i in range(len(pred_arr_scaled)//6):  # make the loop for 14 time slots (2 different time slot x 7days)
    # creating pre_seq
    pred_seq = []
    for t in range(5):  #  Do the "difference" 5 times every loop
        k = i*6 + t + 1  # Add 1 is for starting it from index 1 in every 6-space time slot, to ignore the first index which is non-stationary
        pred_seq.append(pred_arr_scaled[k])  # creating a sequence for a time slot
    
    # creating feedin_weather_seq
    feedin_weather_seq = []
    for t in range(6):  #  Do 6 times every loop
        k = i*6 + t  #
        feedin_weather_seq.append(feedin_weather_arr_scaled[k])


    pred_seq = np.stack(pred_seq)  # change back to the numpy array (2D)
    pred_seq = pred_seq.reshape(1, pred_seq.shape[0], pred_seq.shape[1])  # change to numpy 3D as input

    feedin_weather_seq = np.stack(feedin_weather_seq)  # change back to the numpy array (2D)
    feedin_weather_seq = feedin_weather_seq.reshape(1, feedin_weather_seq.shape[0], feedin_weather_seq.shape[1])  # change to numpy 3D as input

    for q in range(6):
        # predict next timestamp
        output_pred = model.predict(pred_seq)  # get one prediction output (size (1 x output feature(s)))
        ans_arr.append(output_pred)

        # update the input seq
        for j in range(1,5):
            pred_seq[0][j-1] = pred_seq[0][j]
        pred_seq[0][4] = feedin_weather_seq[0][q]
        pred_seq[0][4][0:output_dim] = output_pred[0]

In [28]:
# 10. Backward to the non-stationary, correct scale output

#  Helper functions

def backward_scaler(nn_output):
    tmp = np.zeros(14)
    tmp[0:output_dim] = nn_output
    tmp = scaler.inverse_transform(tmp)
    return tmp[0:output_dim]

def decode(last_timestamp_values, nn_output):
    tmp = np.zeros(input_dim)
    tmp[0:output_dim] = nn_output
    tmp = scaler.inverse_transform(tmp)
    return last_timestamp_values + tmp[0:output_dim]

# create the non-stationary 6:40 and 16:40 for decoding
df_non_station_sel_time = df_pred_sel[ ((df_pred_sel.timeofday>= 7.5) & (df_pred_sel.timeofday<8)) |
                            ((df_pred_sel.timeofday>=16.5) & (df_pred_sel.timeofday<17))]

In [29]:
''' Output the non-stationary Answers (allAns)'''

tmp = df_non_station_sel_time[using_cols[0:output_dim]].values
allAns = []
for i in range(len(tmp)):
    seed = tmp[i]  # non-stationary for reconstructing a sequence
    segmentAns = []
    for timestep in range(6):
        seed = decode(seed, ans_arr[i*6+timestep])
        segmentAns.append(seed)
    allAns.append(segmentAns)

# Change back to np array for easy visualize
allAns = np.array(allAns)

/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
/Users/Kin/anaconda/lib/python3.5/site-packages/sklearn/preprocessing/data.py:374: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)

In [30]:
# Checking
for i in allAns:
    print(i)

[[ 66.76982747]
 [ 70.09885534]
 [ 72.89891696]
 [ 76.28864959]
 [ 79.11878913]
 [ 81.90569521]]
[[ 79.91970618]
 [ 83.31672641]
 [ 80.95269945]
 [ 82.84962857]
 [ 84.56913774]
 [ 82.84170637]]
[[ 70.06536112]
 [ 71.23951167]
 [ 75.18064122]
 [ 78.08522786]
 [ 81.09901494]
 [ 83.87094831]]
[[ 63.94844604]
 [ 66.68606144]
 [ 66.18116769]
 [ 66.46409199]
 [ 68.0327005 ]
 [ 67.24631607]]
[[ 75.51253007]
 [ 79.94245888]
 [ 82.35896555]
 [ 86.04158402]
 [ 88.8995868 ]
 [ 91.71980763]]
[[ 65.7643104 ]
 [ 66.04645862]
 [ 66.00532129]
 [ 66.95043296]
 [ 67.31342622]
 [ 67.28283225]]
[[ 69.15555619]
 [ 72.69113548]
 [ 75.03063966]
 [ 78.21906415]
 [ 81.52738388]
 [ 84.29049641]]
[[ 86.26252495]
 [ 85.52518513]
 [ 84.43928977]
 [ 87.9626789 ]
 [ 87.19183504]
 [ 87.33756316]]
[[ 77.85302257]
 [ 80.78467744]
 [ 82.38465103]
 [ 84.79305616]
 [ 88.33792951]
 [ 91.29358614]]
[[ 72.26712642]
 [ 71.2891822 ]
 [ 71.1452613 ]
 [ 74.06671353]
 [ 73.79610195]
 [ 73.97376301]]
[[ 64.54264199]
 [ 68.68339502]
 [ 73.96057841]
 [ 76.89325544]
 [ 81.04799687]
 [ 85.03690279]]
[[ 76.99498584]
 [ 81.58194826]
 [ 80.75613507]
 [ 83.5797063 ]
 [ 86.29911216]
 [ 87.26972097]]
[[ 74.07598332]
 [ 78.57642204]
 [ 80.86866092]
 [ 84.93085928]
 [ 88.57120967]
 [ 92.41190283]]
[[ 71.97746514]
 [ 73.90903403]
 [ 76.48435361]
 [ 80.04071677]
 [ 84.57498131]
 [ 88.33793375]]

In [31]:
# 11. Output the CSV file

# create the datetime objects
import datetime

pred_start_date = 18


start_8am = datetime.datetime(year=2016, month=10, day=pred_start_date, hour=8, minute=0, second=0)
start_5pm = datetime.datetime(year=2016, month=10, day=pred_start_date, hour=17, minute=0, second=0)
add_1_day = datetime.timedelta(days=1)
add_20_min = datetime.timedelta(minutes=20)

'''
allAns[x,y,z]
[x]: Segment (AM & PM, total 14)
[y]: timestamp (6 [20mins])
[z]: 3 features
'''
# allAns[0,:,1]

'\nallAns[x,y,z]\n[x]: Segment (AM & PM, total 14)\n[y]: timestamp (6 [20mins])\n[z]: 3 features\n'

In [32]:
# 11.a [FOR TRAFFIC TIME] Output the CSV file

route = 'A'
checkpoint = '2'
vol_or_traj = 0  # select the output cell

with open('{}-{}_checking.csv'.format(route, checkpoint), 'w') as f:
    for day in range(7):
        for am_pm in range(2):
            if am_pm == 0:
                ref_time = start_8am
            else:
                ref_time = start_5pm
            for timestep in range(6):
                start_timestamp = ref_time + day*add_1_day + timestep*add_20_min
                end_timestamp = start_timestamp + add_20_min
                start_timestr = start_timestamp.strftime("%Y-%m-%d %H:%M:00")
                end_timestr = end_timestamp.strftime("%Y-%m-%d %H:%M:00")
                f.write('{},{},"[{},{})",{}\n'.format(route,
                                                      checkpoint,
                                                      start_timestr,
                                                      end_timestr,
                                                      allAns[day*2+am_pm, timestep, vol_or_traj ]))

In [364]:
# 11.b [FOR VOLUME] Output the CSV file

checkpoint = '2'
direction = '0'
vol_or_traj = 1  # select the output cell

with open('{}-{}.csv'.format(checkpoint, direction), 'w') as f:
    for day in range(7):
        for am_pm in range(2):
            if am_pm == 0:
                ref_time = start_8am
            else:
                ref_time = start_5pm
            for timestep in range(6):
                start_timestamp = ref_time + day*add_1_day + timestep*add_20_min
                end_timestamp = start_timestamp + add_20_min
                start_timestr = start_timestamp.strftime("%Y-%m-%d %H:%M:00")
                end_timestr = end_timestamp.strftime("%Y-%m-%d %H:%M:00")
                f.write('{},"[{},{})",{},{}\n'.format(checkpoint,
                                                  start_timestr,
                                                  end_timestr,
                                                  direction,
                                                  allAns[day*2+am_pm, timestep, vol_or_traj ]))