In [281]:
import csv
import pandas as pd
import numpy as np
import pickle

# 1. Link

In [282]:
# get the link file
df_link = pd.read_csv('links (table 3).csv')
df_link

    link_id  length  width  lanes   in_top  out_top  lane_width
0       100      58      3      1      105      111           3
1       101      84      3      1      116      121           3
2       102     131      9      3      115      109           3
3       103      23     12      4      111  122,116           3
4       104     293      9      3      109      112           3
5       105      78      6      2      NaN      100           3
6       106      15      3      1      121      113           3
7       107      34      9      3      123      108           3
8       108      40      9      3      107  119,120           3
9       109     135      9      3      102      104           3
10      110     109      9      3      NaN      123           3
11      111     121     12      4  100,112      103           3
12      112     199      9      3      104      111           3
13      113     144      6      2      106      NaN           3
14      114     198      3      1      119      118           3
15      115     107      9      3      NaN      102           3
16      116     180      9      3  118,103      101           3
17      117     136      3      1      120      NaN           3
18      118     206      9      3      114  116,122           3
19      119       9      3      1      108      114           3
20      120       6      3      1      108      117           3
21      121     118      3      1      101      106           3
22      122     197      3      1  118,103      NaN           3
23      123      59      9      3      110      107           3

# 2. Route

In [283]:
# get the route file
df_routes = pd.read_csv('routes (table 4).csv')
df_routes

,intersection_id,tollgate_id,link_seq
0,A,2,"110,123,107,108,120,117"
1,A,3,"110,123,107,108,119,114,118,122"
2,B,1,"105,100,111,103,116,101,121,106,113"
3,B,3,"105,100,111,103,122"
4,C,1,"115,102,109,104,112,111,103,116,101,121,106,113"
5,C,3,"115,102,109,104,112,111,103,122"

# 3. Trajectories

In [284]:
# get the df_trajectories file
df_trajectories = pd.read_csv('trajectories(table 5)_training.csv')
# extract the travel sequence for routes
df_travel_seq = pd.DataFrame(df_trajectories.iloc[:,4].str.replace(';','#').str.split('#'))
df_trajectories

,intersection_id,tollgate_id,vehicle_id,starting_time,travel_seq,travel_time
0,B,3,1065642,2016-07-19 00:14:24,105#2016-07-19 00:14:24#9.56;100#2016-07-19 00...,70.85
1,B,3,1047198,2016-07-19 00:35:56,105#2016-07-19 00:35:56#11.58;100#2016-07-19 0...,148.79
2,B,1,1086390,2016-07-19 00:37:15,105#2016-07-19 00:37:15#5.26;100#2016-07-19 00...,79.76
3,A,2,1071181,2016-07-19 00:37:59,110#2016-07-19 00:37:59#13.74;123#2016-07-19 0...,58.05
4,B,1,1065807,2016-07-19 00:56:21,105#2016-07-19 00:56:21#16.08;100#2016-07-19 0...,137.98
5,C,3,1072812,2016-07-19 00:56:31,115#2016-07-19 00:56:31#10.97;102#2016-07-19 0...,113.54
6,B,1,1014648,2016-07-19 01:26:03,105#2016-07-19 01:26:03#16.85;100#2016-07-19 0...,176.70
7,A,2,1063919,2016-07-19 01:36:04,110#2016-07-19 01:36:04#10.39;123#2016-07-19 0...,74.47
8,A,3,1064408,2016-07-19 01:36:20,110#2016-07-19 01:36:20#8.58;123#2016-07-19 01...,94.57
9,C,1,1056529,2016-07-19 01:36:28,115#2016-07-19 01:36:28#9.50;102#2016-07-19 01...,214.87
10,A,2,1002179,2016-07-19 01:38:48,110#2016-07-19 01:38:48#8.25;123#2016-07-19 01...,39.27
11,B,3,1056879,2016-07-19 01:40:40,105#2016-07-19 01:40:40#11.40;100#2016-07-19 0...,86.07
12,A,2,1004088,2016-07-19 01:42:22,110#2016-07-19 01:42:22#8.32;123#2016-07-19 01...,35.38
13,C,1,1063652,2016-07-19 01:44:57,115#2016-07-19 01:44:57#7.47;102#2016-07-19 01...,189.77
14,C,1,1057504,2016-07-19 01:46:36,115#2016-07-19 01:46:36#6.77;102#2016-07-19 01...,131.50
15,A,2,1022331,2016-07-19 01:48:40,110#2016-07-19 01:48:40#9.51;123#2016-07-19 01...,130.43
16,B,3,1053843,2016-07-19 01:48:47,105#2016-07-19 01:48:47#34.41;100#2016-07-19 0...,101.37
17,A,2,1004286,2016-07-19 01:52:08,110#2016-07-19 01:52:08#18.05;123#2016-07-19 0...,67.41
18,B,3,1086111,2016-07-19 02:10:44,105#2016-07-19 02:10:44#5.17;100#2016-07-19 02...,67.81
19,A,2,1065328,2016-07-19 02:20:16,110#2016-07-19 02:20:16#10.07;123#2016-07-19 0...,42.64
20,A,3,1054620,2016-07-19 02:36:20,110#2016-07-19 02:36:20#7.42;123#2016-07-19 02...,72.12
21,A,3,1011942,2016-07-19 02:38:10,110#2016-07-19 02:38:10#8.22;123#2016-07-19 02...,83.10
22,B,3,1058173,2016-07-19 02:42:15,105#2016-07-19 02:42:15#17.66;100#2016-07-19 0...,142.32
23,A,2,1027642,2016-07-19 02:42:22,110#2016-07-19 02:42:22#6.65;123#2016-07-19 02...,29.15
24,A,2,1005189,2016-07-19 02:42:24,110#2016-07-19 02:42:24#7.54;123#2016-07-19 02...,40.12
25,B,3,1043567,2016-07-19 02:44:00,105#2016-07-19 02:44:00#11.50;100#2016-07-19 0...,192.77
26,A,2,1056068,2016-07-19 02:58:39,110#2016-07-19 02:58:39#9.42;123#2016-07-19 02...,51.25
27,A,3,1017831,2016-07-19 03:12:37,110#2016-07-19 03:12:37#7.48;123#2016-07-19 03...,93.09
28,A,2,1055860,2016-07-19 03:27:36,110#2016-07-19 03:27:36#11.44;123#2016-07-19 0...,44.29
29,A,2,1085652,2016-07-19 03:36:02,110#2016-07-19 03:36:02#11.39;123#2016-07-19 0...,39.55
...,...,...,...,...,...,...
109214,C,1,1020280,2016-10-17 22:35:53,115#2016-10-17 22:35:53#12.38;102#2016-10-17 2...,117.84
109215,C,3,1016880,2016-10-17 22:42:49,115#2016-10-17 22:42:49#8.47;102#2016-10-17 22...,189.38
109216,A,2,1045083,2016-10-17 22:45:00,110#2016-10-17 22:45:00#19.22;123#2016-10-17 2...,67.98
109217,A,3,1011400,2016-10-17 22:50:11,110#2016-10-17 22:50:11#10.77;123#2016-10-17 2...,83.76
109218,A,2,1043473,2016-10-17 22:50:23,110#2016-10-17 22:50:23#9.96;123#2016-10-17 22...,53.01
109219,B,3,1035615,2016-10-17 22:51:12,105#2016-10-17 22:51:12#8.30;100#2016-10-17 22...,60.92
109220,A,2,1027124,2016-10-17 22:56:18,110#2016-10-17 22:56:18#8.83;123#2016-10-17 22...,46.50
109221,C,3,1043900,2016-10-17 22:57:13,115#2016-10-17 22:57:13#7.75;102#2016-10-17 22...,111.67
109222,A,2,1022578,2016-10-17 23:06:06,110#2016-10-17 23:06:06#10.28;123#2016-10-17 2...,45.52
109223,B,3,1049127,2016-10-17 23:07:24,105#2016-10-17 23:07:24#9.49;100#2016-10-17 23...,60.49
109224,A,3,1042839,2016-10-17 23:08:13,110#2016-10-17 23:08:13#9.63;123#2016-10-17 23...,104.54
109225,A,2,1002950,2016-10-17 23:08:18,110#2016-10-17 23:08:18#10.31;123#2016-10-17 2...,48.36
109226,A,3,1018469,2016-10-17 23:10:45,110#2016-10-17 23:10:45#9.21;123#2016-10-17 23...,102.83
109227,C,1,1048639,2016-10-17 23:13:29,115#2016-10-17 23:13:29#7.28;102#2016-10-17 23...,194.33
109228,A,2,1000448,2016-10-17 23:14:16,110#2016-10-17 23:14:16#12.20;123#2016-10-17 2...,48.04
109229,A,2,1004272,2016-10-17 23:14:17,110#2016-10-17 23:14:17#11.13;123#2016-10-17 2...,61.68
109230,C,1,1031989,2016-10-17 23:20:17,115#2016-10-17 23:20:17#9.86;102#2016-10-17 23...,159.78
109231,A,2,1010568,2016-10-17 23:21:50,110#2016-10-17 23:21:50#13.24;123#2016-10-17 2...,40.29
109232,A,2,1037457,2016-10-17 23:22:08,110#2016-10-17 23:22:08#31.53;123#2016-10-17 2...,123.37
109233,A,2,1009417,2016-10-17 23:22:19,110#2016-10-17 23:22:19#22.78;123#2016-10-17 2...,124.41
109234,B,3,1047183,2016-10-17 23:29:43,105#2016-10-17 23:29:43#20.17;100#2016-10-17 2...,131.68
109235,A,2,1012726,2016-10-17 23:30:10,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54
109236,A,3,1004601,2016-10-17 23:30:43,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87
109237,A,3,1035614,2016-10-17 23:35:56,110#2016-10-17 23:35:56#11.74;123#2016-10-17 2...,91.59
109238,B,1,1003456,2016-10-17 23:37:31,105#2016-10-17 23:37:31#9.95;100#2016-10-17 23...,97.54
109239,A,2,1027763,2016-10-17 23:38:52,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46
109240,A,2,1051052,2016-10-17 23:40:19,110#2016-10-17 23:40:19#11.87;123#2016-10-17 2...,42.27
109241,A,3,1003251,2016-10-17 23:52:18,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94
109242,A,3,1041002,2016-10-17 23:53:57,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51
109243,A,3,1017582,2016-10-17 23:54:35,110#2016-10-17 23:54:35#9.10;123#2016-10-17 23...,137.38

# A travel sequence example from the trajectries

In [285]:
df_travel_seq.iloc[0][0]

['105',
 '2016-07-19 00:14:24',
 '9.56',
 '100',
 '2016-07-19 00:14:34',
 '6.75',
 '111',
 '2016-07-19 00:14:41',
 '13.00',
 '103',
 '2016-07-19 00:14:54',
 '7.47',
 '122',
 '2016-07-19 00:15:02',
 '32.85']

# 4. Volume

In [286]:
# get the volume file
df_volume = pd.read_csv('volume(table 6)_training.csv')

# turns the nan to 0 (refer to Q&A)
df_volume['vehicle_type'] = df_volume['vehicle_type'].fillna(0)

df_volume

,time,tollgate_id,direction,vehicle_model,has_etc,vehicle_type
0,19/9/2016 23:09,2,0,1,0,0.0
1,28/9/2016 8:42,1,1,1,0,0.0
2,28/9/2016 8:50,1,1,1,1,0.0
3,28/9/2016 8:44,3,1,1,1,0.0
4,28/9/2016 8:44,3,1,1,0,0.0
5,28/9/2016 8:45,3,1,1,0,0.0
6,28/9/2016 8:45,3,1,1,0,0.0
7,28/9/2016 8:46,3,1,1,1,0.0
8,28/9/2016 8:47,1,1,1,0,0.0
9,28/9/2016 8:48,3,1,1,0,0.0
10,28/9/2016 8:45,3,1,1,1,0.0
11,28/9/2016 8:46,3,1,1,1,0.0
12,28/9/2016 8:47,3,1,1,0,0.0
13,28/9/2016 8:48,3,1,1,1,0.0
14,28/9/2016 8:48,3,1,1,1,0.0
15,28/9/2016 8:45,1,1,1,0,0.0
16,28/9/2016 8:46,1,1,1,0,0.0
17,28/9/2016 8:46,1,1,1,0,0.0
18,28/9/2016 8:47,1,1,1,0,1.0
19,28/9/2016 8:49,3,1,1,0,0.0
20,28/9/2016 8:45,1,1,1,1,0.0
21,28/9/2016 8:46,1,1,1,1,0.0
22,28/9/2016 8:46,3,1,1,0,0.0
23,28/9/2016 8:46,3,1,1,0,0.0
24,28/9/2016 8:50,3,1,1,1,0.0
25,28/9/2016 8:45,1,1,1,1,0.0
26,28/9/2016 8:46,1,1,5,0,1.0
27,28/9/2016 8:48,3,1,3,1,0.0
28,28/9/2016 8:48,3,1,1,1,0.0
29,28/9/2016 8:45,3,1,1,0,0.0
...,...,...,...,...,...,...
415521,28/9/2016 8:41,1,1,1,1,0.0
415522,28/9/2016 8:41,1,1,1,1,0.0
415523,28/9/2016 8:44,3,1,5,0,1.0
415524,28/9/2016 8:45,3,1,1,1,0.0
415525,28/9/2016 8:40,1,1,1,0,0.0
415526,28/9/2016 8:40,3,1,1,1,0.0
415527,28/9/2016 8:41,3,1,1,0,0.0
415528,28/9/2016 8:44,3,1,1,0,0.0
415529,28/9/2016 8:44,3,1,1,0,0.0
415530,28/9/2016 8:45,3,1,1,1,0.0
415531,28/9/2016 8:45,1,1,1,0,0.0
415532,28/9/2016 8:40,1,1,1,0,1.0
415533,28/9/2016 8:40,1,1,1,0,0.0
415534,28/9/2016 8:41,3,1,1,0,0.0
415535,28/9/2016 8:41,3,1,1,0,0.0
415536,28/9/2016 8:41,3,1,1,0,0.0
415537,28/9/2016 8:43,3,1,1,0,1.0
415538,28/9/2016 8:44,1,1,1,0,0.0
415539,28/9/2016 8:40,1,1,1,0,0.0
415540,28/9/2016 8:43,1,1,1,1,0.0
415541,28/9/2016 8:40,1,1,1,0,0.0
415542,28/9/2016 8:41,3,1,1,0,0.0
415543,28/9/2016 8:41,3,1,1,0,0.0
415544,28/9/2016 8:44,3,1,1,1,0.0
415545,28/9/2016 8:44,3,1,1,0,0.0
415546,28/9/2016 8:44,3,1,1,0,0.0
415547,28/9/2016 8:44,3,1,1,0,0.0
415548,28/9/2016 8:45,3,1,1,0,0.0
415549,28/9/2016 8:41,1,1,1,0,0.0
415550,28/9/2016 8:41,1,1,1,0,0.0

# 5. Weather

In [287]:
# get the weather file
df_weather = pd.read_csv('weather (table 7)_training_update.csv')
df_weather

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
0,2016-07-01,0,1000.4,1005.3,225.0,2.1,26.4,94.0,0.0
1,2016-07-01,3,1000.5,1005.3,187.0,2.7,29.0,76.0,0.0
2,2016-07-01,6,998.9,1003.7,212.0,2.9,31.7,67.0,0.0
3,2016-07-01,9,998.7,1003.5,244.0,2.7,31.6,59.0,0.0
4,2016-07-01,12,999.7,1004.5,222.0,1.3,29.9,68.0,0.0
5,2016-07-01,15,1000.0,1004.8,102.0,1.6,27.8,82.0,0.0
6,2016-07-01,18,998.8,1003.6,202.0,1.9,26.0,89.0,0.0
7,2016-07-01,21,1000.2,1005.0,334.0,2.2,25.5,90.0,0.0
8,2016-07-02,0,1001.6,1006.4,315.0,1.8,26.8,82.0,0.0
9,2016-07-02,3,1002.4,1007.2,46.0,3.2,30.0,70.0,0.0
10,2016-07-02,6,1001.3,1006.2,37.0,2.2,29.3,80.0,1.0
11,2016-07-02,9,1001.9,1006.8,345.0,2.4,25.9,95.0,10.2
12,2016-07-02,12,1003.6,1008.5,113.0,1.0,25.1,94.0,0.2
13,2016-07-02,15,1002.4,1007.3,138.0,1.0,25.3,96.0,0.0
14,2016-07-02,18,1000.9,1005.8,221.0,0.7,25.4,96.0,0.0
15,2016-07-02,21,1000.9,1005.8,999017.0,0.1,25.2,98.0,0.0
16,2016-07-03,0,1001.5,1006.4,220.0,1.5,25.8,97.0,0.0
17,2016-07-03,3,1001.5,1006.4,200.0,1.6,27.0,93.0,0.1
18,2016-07-03,6,1000.8,1005.7,207.0,1.8,27.4,92.0,0.0
19,2016-07-03,9,1000.8,1005.7,223.0,1.1,27.7,91.0,0.1
20,2016-07-03,12,1001.6,1006.5,137.0,0.6,26.9,91.0,0.0
21,2016-07-03,15,1002.2,1007.1,173.0,0.4,26.0,96.0,0.1
22,2016-07-03,18,1000.5,1005.4,330.0,0.7,25.7,98.0,0.4
23,2016-07-03,21,1000.4,1005.3,999017.0,0.0,25.7,98.0,0.0
24,2016-07-04,0,1000.6,1005.5,176.0,2.0,26.3,97.0,0.0
25,2016-07-04,3,1000.5,1005.3,179.0,2.1,31.8,69.0,0.0
26,2016-07-04,6,999.7,1004.5,160.0,1.7,34.7,56.0,0.0
27,2016-07-04,9,998.8,1003.6,287.0,1.4,34.8,55.0,0.0
28,2016-07-04,12,1001.1,1006.0,340.0,1.0,29.7,78.0,0.0
29,2016-07-04,15,1001.1,1005.9,188.0,1.3,27.8,79.0,0.0
...,...,...,...,...,...,...,...,...,...
832,2016-10-14,6,1015.8,1020.9,359.0,1.9,18.5,84.0,0.0
833,2016-10-14,9,1015.5,1020.6,349.0,2.0,18.2,81.0,0.0
834,2016-10-14,12,1016.5,1021.6,1.0,1.4,18.3,83.0,0.0
835,2016-10-14,15,1015.9,1021.0,354.0,1.8,18.2,87.0,0.0
836,2016-10-14,18,1015.4,1020.5,202.0,1.1,18.4,89.0,0.0
837,2016-10-14,21,1015.2,1020.3,360.0,2.3,18.5,90.0,0.0
838,2016-10-15,0,1016.5,1021.6,35.0,2.0,19.0,95.0,0.0
839,2016-10-15,3,1015.8,1020.9,357.0,1.1,19.8,94.0,0.6
840,2016-10-15,6,1013.7,1018.8,334.0,1.5,20.3,96.0,0.1
841,2016-10-15,9,1013.7,1018.8,333.0,2.2,20.3,96.0,0.0
842,2016-10-15,12,1014.5,1019.6,344.0,0.9,20.0,97.0,0.0
843,2016-10-15,15,1013.9,1019.0,999017.0,0.0,19.8,97.0,0.0
844,2016-10-15,18,1012.9,1017.9,215.0,1.7,19.7,97.0,0.0
845,2016-10-15,21,1012.8,1017.8,216.0,3.2,19.6,97.0,0.0
846,2016-10-16,0,1013.9,1018.9,327.0,0.6,20.4,95.0,0.0
847,2016-10-16,3,1013.9,1018.9,342.0,2.2,24.6,76.0,0.0
848,2016-10-16,6,1011.7,1016.7,301.0,1.8,26.8,67.0,0.0
849,2016-10-16,9,1011.7,1016.7,10.0,4.1,24.9,74.0,0.0
850,2016-10-16,12,1013.8,1018.8,353.0,4.3,22.7,77.0,0.0
851,2016-10-16,15,1014.7,1019.7,7.0,2.1,21.9,80.0,0.0
852,2016-10-16,18,1014.5,1019.5,344.0,2.0,21.3,83.0,0.0
853,2016-10-16,21,1014.2,1019.2,35.0,3.0,20.4,81.0,0.0
854,2016-10-17,0,1015.6,1020.6,35.0,2.1,20.1,80.0,0.0
855,2016-10-17,3,1015.6,1020.6,104.0,1.5,19.6,90.0,0.1
856,2016-10-17,6,1013.4,1018.4,81.0,1.2,21.3,79.0,0.0
857,2016-10-17,9,1013.7,1018.7,109.0,1.1,20.9,79.0,0.0
858,2016-10-17,12,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0
859,2016-10-17,15,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0
860,2016-10-17,18,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0
861,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0

# Join 1 : Trajectories - Volume

In [288]:
# natural join / overlapping of df_trajectories and df_volume on the same 'time'
df_trajectories = df_trajectories.rename(columns={"starting_time":"time"})
df_trajectories['time'] = pd.to_datetime(df_trajectories['time'], format='%Y-%m-%d %H:%M')
df_trajectories['time'] = df_trajectories['time'].map(lambda t: t.strftime('%Y-%m-%d %H:%M'))
df_trajectories['time'] = pd.to_datetime(df_trajectories['time'], format='%Y-%m-%d %H:%M')
df_volume['time'] = pd.to_datetime(df_volume['time'], format='%d/%m/%Y %H:%M')
df_trajectories_volume = pd.merge(df_trajectories, df_volume, on=['time'])
df_trajectories_volume

,intersection_id,tollgate_id_x,vehicle_id,time,travel_seq,travel_time,tollgate_id_y,direction,vehicle_model,has_etc,vehicle_type
0,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,1,1,1,0,0.0
1,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,1,0,0.0
2,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,1,1,1,1,0.0
3,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,1,0,0.0
4,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,1,0,0.0
5,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,1,1,1,0,0.0
6,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,2,0,1.0
7,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,1,0,0.0
8,A,3,1046053,2016-09-19 00:02:00,110#2016-09-19 00:02:21#6.32;123#2016-09-19 00...,65.93,3,1,1,0,0.0
9,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,1,1,1,0,0.0
10,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,1,0,0.0
11,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,1,1,1,1,0.0
12,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,1,0,0.0
13,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,1,0,0.0
14,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,1,1,1,0,0.0
15,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,2,0,1.0
16,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,1,0,0.0
17,C,3,1040332,2016-09-19 00:02:00,115#2016-09-19 00:02:40#9.75;102#2016-09-19 00...,151.44,3,1,1,0,0.0
18,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,1,1,1,0,0.0
19,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,1,0,0.0
20,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,1,1,1,1,0.0
21,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,1,0,0.0
22,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,1,0,0.0
23,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,1,1,1,0,0.0
24,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,2,0,1.0
25,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,1,0,0.0
26,A,2,1013860,2016-09-19 00:02:00,110#2016-09-19 00:02:49#8.23;123#2016-09-19 00...,100.19,3,1,1,0,0.0
27,A,3,1018895,2016-09-19 00:12:00,110#2016-09-19 00:12:38#11.54;123#2016-09-19 0...,69.11,1,1,1,0,0.0
28,A,3,1018895,2016-09-19 00:12:00,110#2016-09-19 00:12:38#11.54;123#2016-09-19 0...,69.11,1,1,1,0,0.0
29,A,3,1018895,2016-09-19 00:12:00,110#2016-09-19 00:12:38#11.54;123#2016-09-19 0...,69.11,1,1,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
694453,B,3,1047183,2016-10-17 23:29:00,105#2016-10-17 23:29:43#20.17;100#2016-10-17 2...,131.68,1,1,1,1,0.0
694454,A,2,1012726,2016-10-17 23:30:00,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54,1,1,2,0,1.0
694455,A,2,1012726,2016-10-17 23:30:00,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54,3,0,1,0,0.0
694456,A,2,1012726,2016-10-17 23:30:00,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54,2,0,2,0,0.0
694457,A,2,1012726,2016-10-17 23:30:00,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54,1,0,1,0,0.0
694458,A,2,1012726,2016-10-17 23:30:00,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54,2,0,1,0,0.0
694459,A,3,1004601,2016-10-17 23:30:00,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87,1,1,2,0,1.0
694460,A,3,1004601,2016-10-17 23:30:00,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87,3,0,1,0,0.0
694461,A,3,1004601,2016-10-17 23:30:00,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87,2,0,2,0,0.0
694462,A,3,1004601,2016-10-17 23:30:00,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87,1,0,1,0,0.0
694463,A,3,1004601,2016-10-17 23:30:00,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87,2,0,1,0,0.0
694464,A,3,1035614,2016-10-17 23:35:00,110#2016-10-17 23:35:56#11.74;123#2016-10-17 2...,91.59,3,1,1,0,1.0
694465,A,3,1035614,2016-10-17 23:35:00,110#2016-10-17 23:35:56#11.74;123#2016-10-17 2...,91.59,1,0,1,1,0.0
694466,B,1,1003456,2016-10-17 23:37:00,105#2016-10-17 23:37:31#9.95;100#2016-10-17 23...,97.54,2,0,2,0,0.0
694467,A,2,1027763,2016-10-17 23:38:00,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46,3,1,1,1,0.0
694468,A,2,1027763,2016-10-17 23:38:00,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46,3,1,1,1,0.0
694469,A,2,1027763,2016-10-17 23:38:00,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46,1,1,1,0,1.0
694470,A,2,1027763,2016-10-17 23:38:00,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46,3,1,1,0,0.0
694471,A,2,1051052,2016-10-17 23:40:00,110#2016-10-17 23:40:19#11.87;123#2016-10-17 2...,42.27,3,1,1,0,0.0
694472,A,2,1051052,2016-10-17 23:40:00,110#2016-10-17 23:40:19#11.87;123#2016-10-17 2...,42.27,1,1,1,0,0.0
694473,A,2,1051052,2016-10-17 23:40:00,110#2016-10-17 23:40:19#11.87;123#2016-10-17 2...,42.27,3,0,1,0,0.0
694474,A,3,1003251,2016-10-17 23:52:00,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94,1,1,1,0,0.0
694475,A,3,1003251,2016-10-17 23:52:00,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94,3,1,1,0,0.0
694476,A,3,1003251,2016-10-17 23:52:00,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94,3,1,5,0,1.0
694477,A,3,1003251,2016-10-17 23:52:00,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94,1,0,1,1,0.0
694478,A,3,1041002,2016-10-17 23:53:00,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51,3,1,1,0,0.0
694479,A,3,1041002,2016-10-17 23:53:00,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51,3,1,1,0,0.0
694480,A,3,1041002,2016-10-17 23:53:00,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51,3,0,1,0,0.0
694481,A,3,1041002,2016-10-17 23:53:00,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51,3,0,2,0,0.0
694482,A,3,1017582,2016-10-17 23:54:00,110#2016-10-17 23:54:35#9.10;123#2016-10-17 23...,137.38,2,0,2,0,0.0

# Join 2 : Weather - Trajectories

In [289]:
# natural join / overlapping of df_trajectories and df_weather on the same 'time'
# find the date for each trajectories
date_trajectories = df_trajectories['time'].map(lambda t: t.strftime('%Y-%m-%d'))
# add the "date_trajectories" column for the data file df_trajectories
df_trajectories['date'] = date_trajectories
df_trajectories['hour'] = pd.to_datetime(df_trajectories['time'].map(lambda t: t.strftime('%H:%M'))).apply(lambda t: t.hour)
df_trajectories['time'] = df_trajectories['time'].map(lambda t: t.strftime('%H:%M'))
df_trajectories['hour']=(np.floor(df_trajectories['hour']/3)*3).astype(int)
df_weather_trajectories = pd.merge(df_weather, df_trajectories, on=['date','hour'])
df_weather_trajectories

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,intersection_id,tollgate_id,vehicle_id,time,travel_seq,travel_time
0,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1065642,00:14,105#2016-07-19 00:14:24#9.56;100#2016-07-19 00...,70.85
1,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1047198,00:35,105#2016-07-19 00:35:56#11.58;100#2016-07-19 0...,148.79
2,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,1,1086390,00:37,105#2016-07-19 00:37:15#5.26;100#2016-07-19 00...,79.76
3,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1071181,00:37,110#2016-07-19 00:37:59#13.74;123#2016-07-19 0...,58.05
4,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,1,1065807,00:56,105#2016-07-19 00:56:21#16.08;100#2016-07-19 0...,137.98
5,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,C,3,1072812,00:56,115#2016-07-19 00:56:31#10.97;102#2016-07-19 0...,113.54
6,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,1,1014648,01:26,105#2016-07-19 01:26:03#16.85;100#2016-07-19 0...,176.70
7,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1063919,01:36,110#2016-07-19 01:36:04#10.39;123#2016-07-19 0...,74.47
8,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,3,1064408,01:36,110#2016-07-19 01:36:20#8.58;123#2016-07-19 01...,94.57
9,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,C,1,1056529,01:36,115#2016-07-19 01:36:28#9.50;102#2016-07-19 01...,214.87
10,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1002179,01:38,110#2016-07-19 01:38:48#8.25;123#2016-07-19 01...,39.27
11,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1056879,01:40,105#2016-07-19 01:40:40#11.40;100#2016-07-19 0...,86.07
12,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1004088,01:42,110#2016-07-19 01:42:22#8.32;123#2016-07-19 01...,35.38
13,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,C,1,1063652,01:44,115#2016-07-19 01:44:57#7.47;102#2016-07-19 01...,189.77
14,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,C,1,1057504,01:46,115#2016-07-19 01:46:36#6.77;102#2016-07-19 01...,131.50
15,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1022331,01:48,110#2016-07-19 01:48:40#9.51;123#2016-07-19 01...,130.43
16,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1053843,01:48,105#2016-07-19 01:48:47#34.41;100#2016-07-19 0...,101.37
17,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1004286,01:52,110#2016-07-19 01:52:08#18.05;123#2016-07-19 0...,67.41
18,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1086111,02:10,105#2016-07-19 02:10:44#5.17;100#2016-07-19 02...,67.81
19,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1065328,02:20,110#2016-07-19 02:20:16#10.07;123#2016-07-19 0...,42.64
20,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,3,1054620,02:36,110#2016-07-19 02:36:20#7.42;123#2016-07-19 02...,72.12
21,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,3,1011942,02:38,110#2016-07-19 02:38:10#8.22;123#2016-07-19 02...,83.10
22,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1058173,02:42,105#2016-07-19 02:42:15#17.66;100#2016-07-19 0...,142.32
23,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1027642,02:42,110#2016-07-19 02:42:22#6.65;123#2016-07-19 02...,29.15
24,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1005189,02:42,110#2016-07-19 02:42:24#7.54;123#2016-07-19 02...,40.12
25,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,B,3,1043567,02:44,105#2016-07-19 02:44:00#11.50;100#2016-07-19 0...,192.77
26,2016-07-19,0,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,A,2,1056068,02:58,110#2016-07-19 02:58:39#9.42;123#2016-07-19 02...,51.25
27,2016-07-19,3,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,A,3,1017831,03:12,110#2016-07-19 03:12:37#7.48;123#2016-07-19 03...,93.09
28,2016-07-19,3,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,A,2,1055860,03:27,110#2016-07-19 03:27:36#11.44;123#2016-07-19 0...,44.29
29,2016-07-19,3,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,A,2,1085652,03:36,110#2016-07-19 03:36:02#11.39;123#2016-07-19 0...,39.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107687,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,C,1,1020280,22:35,115#2016-10-17 22:35:53#12.38;102#2016-10-17 2...,117.84
107688,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,C,3,1016880,22:42,115#2016-10-17 22:42:49#8.47;102#2016-10-17 22...,189.38
107689,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1045083,22:45,110#2016-10-17 22:45:00#19.22;123#2016-10-17 2...,67.98
107690,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1011400,22:50,110#2016-10-17 22:50:11#10.77;123#2016-10-17 2...,83.76
107691,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1043473,22:50,110#2016-10-17 22:50:23#9.96;123#2016-10-17 22...,53.01
107692,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,B,3,1035615,22:51,105#2016-10-17 22:51:12#8.30;100#2016-10-17 22...,60.92
107693,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1027124,22:56,110#2016-10-17 22:56:18#8.83;123#2016-10-17 22...,46.50
107694,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,C,3,1043900,22:57,115#2016-10-17 22:57:13#7.75;102#2016-10-17 22...,111.67
107695,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1022578,23:06,110#2016-10-17 23:06:06#10.28;123#2016-10-17 2...,45.52
107696,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,B,3,1049127,23:07,105#2016-10-17 23:07:24#9.49;100#2016-10-17 23...,60.49
107697,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1042839,23:08,110#2016-10-17 23:08:13#9.63;123#2016-10-17 23...,104.54
107698,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1002950,23:08,110#2016-10-17 23:08:18#10.31;123#2016-10-17 2...,48.36
107699,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1018469,23:10,110#2016-10-17 23:10:45#9.21;123#2016-10-17 23...,102.83
107700,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,C,1,1048639,23:13,115#2016-10-17 23:13:29#7.28;102#2016-10-17 23...,194.33
107701,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1000448,23:14,110#2016-10-17 23:14:16#12.20;123#2016-10-17 2...,48.04
107702,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1004272,23:14,110#2016-10-17 23:14:17#11.13;123#2016-10-17 2...,61.68
107703,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,C,1,1031989,23:20,115#2016-10-17 23:20:17#9.86;102#2016-10-17 23...,159.78
107704,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1010568,23:21,110#2016-10-17 23:21:50#13.24;123#2016-10-17 2...,40.29
107705,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1037457,23:22,110#2016-10-17 23:22:08#31.53;123#2016-10-17 2...,123.37
107706,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1009417,23:22,110#2016-10-17 23:22:19#22.78;123#2016-10-17 2...,124.41
107707,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,B,3,1047183,23:29,105#2016-10-17 23:29:43#20.17;100#2016-10-17 2...,131.68
107708,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1012726,23:30,110#2016-10-17 23:30:10#13.46;123#2016-10-17 2...,55.54
107709,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1004601,23:30,110#2016-10-17 23:30:43#9.19;123#2016-10-17 23...,222.87
107710,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1035614,23:35,110#2016-10-17 23:35:56#11.74;123#2016-10-17 2...,91.59
107711,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,B,1,1003456,23:37,105#2016-10-17 23:37:31#9.95;100#2016-10-17 23...,97.54
107712,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1027763,23:38,110#2016-10-17 23:38:52#8.91;123#2016-10-17 23...,52.46
107713,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,2,1051052,23:40,110#2016-10-17 23:40:19#11.87;123#2016-10-17 2...,42.27
107714,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1003251,23:52,110#2016-10-17 23:52:18#7.59;123#2016-10-17 23...,71.94
107715,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1041002,23:53,110#2016-10-17 23:53:57#10.56;123#2016-10-17 2...,132.51
107716,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,A,3,1017582,23:54,110#2016-10-17 23:54:35#9.10;123#2016-10-17 23...,137.38

# Join 3 : Weather - Volume

In [290]:
# natural join / overlapping of df_volume and df_weather on the same 'time'
# find the date for each volume
date_volume = df_volume['time'].map(lambda t: t.strftime('%Y-%m-%d'))
# add the "date_volume" column for the data file df_volume
df_volume['date'] = date_volume
df_volume['hour'] = pd.to_datetime(df_volume['time'].map(lambda t: t.strftime('%H:%M'))).apply(lambda t: t.hour)
df_volume['hour']=(np.floor(df_volume['hour']/3)*3).astype(int)
df_volume['time'] = df_volume['time'].map(lambda t: t.strftime('%H:%M'))
df_weather_volume = pd.merge(df_weather, df_volume, on=['date','hour'])
df_weather_volume

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,time,tollgate_id,direction,vehicle_model,has_etc,vehicle_type
0,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:07,3,1,1,0,0.0
1,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:06,3,1,1,1,0.0
2,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:16,3,1,1,0,0.0
3,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:13,1,1,1,0,0.0
4,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:18,1,1,1,0,0.0
5,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:15,1,1,1,1,0.0
6,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:22,1,1,1,1,0.0
7,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:22,1,1,5,0,1.0
8,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:23,3,1,1,0,0.0
9,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:30,1,1,1,0,0.0
10,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:32,1,1,1,0,0.0
11,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:32,1,1,1,0,1.0
12,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:26,1,1,1,0,0.0
13,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:28,1,1,1,1,0.0
14,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:36,3,1,1,0,0.0
15,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:36,3,1,1,0,0.0
16,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:33,1,1,2,0,1.0
17,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:35,1,1,1,0,0.0
18,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:40,1,1,4,0,1.0
19,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:50,3,1,3,0,1.0
20,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:51,1,1,1,0,0.0
21,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:53,1,1,1,0,0.0
22,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:48,1,1,1,0,0.0
23,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:52,1,1,1,1,0.0
24,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:47,1,1,1,1,0.0
25,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:49,3,1,1,0,0.0
26,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:59,3,1,1,0,1.0
27,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:58,1,1,1,0,0.0
28,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:58,1,1,1,1,0.0
29,2016-09-19,0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,00:59,1,1,2,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395129,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:50,1,0,2,0,0.0
395130,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:53,1,0,1,0,0.0
395131,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:54,1,0,1,0,0.0
395132,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:55,1,0,2,0,0.0
395133,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:55,1,0,1,0,0.0
395134,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:55,1,0,1,0,0.0
395135,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:56,1,0,2,0,0.0
395136,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:56,1,0,1,0,0.0
395137,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:04,1,0,2,0,0.0
395138,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:04,1,0,1,0,0.0
395139,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:06,1,0,1,0,0.0
395140,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:10,1,0,1,0,0.0
395141,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:10,1,0,1,0,0.0
395142,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:10,1,0,1,0,0.0
395143,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:11,1,0,1,0,0.0
395144,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:16,1,0,1,0,0.0
395145,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:17,1,0,1,0,0.0
395146,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:25,1,0,1,0,0.0
395147,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:29,1,0,2,0,0.0
395148,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:30,1,0,1,0,0.0
395149,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:31,1,0,1,0,0.0
395150,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:35,1,0,1,0,0.0
395151,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:35,1,0,2,0,0.0
395152,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:38,1,0,1,0,0.0
395153,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:41,1,0,1,0,0.0
395154,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:43,1,0,1,0,0.0
395155,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:47,1,0,1,0,0.0
395156,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:50,1,0,1,0,0.0
395157,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,23:00,1,0,1,0,0.0
395158,2016-10-17,21,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:04,1,0,1,0,0.0

# Save the join files in pkl format

In [291]:
df_trajectories_volume.to_pickle('trajectories_volume.pkl')
df_weather_trajectories.to_pickle('weather_trajectories.pkl')
df_weather_volume.to_pickle('weather_volume.pkl')